const data = [
  "Partition Array According to Given Pivot",
  "Rearrange Array Elements by Sign",
  "3Sum Closest",
  "4Sum",
  "Sort Colors",
  "Container With Most Water",
  "Watering Plants II",
  "Next Permutation",
  "Next Greater Element III",
  "Reverse Words in a String",
  // "Largest Merge of Two Strings",
  "Make String a Subsequence Using Cyclic Increments",
  "Minimum Length of String After Deleting Similar Ends",
  "String Compression",
  "Separate Black and White Balls",
  "Move Pieces to Obtain a String",
  "Sentence Similarity III",
  "Count Vowel Strings in Ranges",
  "Minimum Penalty for a Shop",
  "Find Good Days to Rob the Bank",
  "Product of Array Except Self",
  "Product of the Last K Numbers",
  "Removing Minimum Number of Magic Beans",
  "Find All Good Indices",
  "Movement of Robots",
  "Range Sum Query 2D - Immutable",
  "Increment Submatrices by One",
  "Minimum Cost to Make Array Equal",
  "Pongal Bunk",
  "Car Pooling",
  "Shifting Letters II",
  "Perfect Rectangle",
  "Rectangle Area II",
  "Number of Flowers in Full Bloom",
  "Set Matrix Zeroes",
  "Minimum Operations to Write the Letter Y on a Grid",
  "Rotate Image",
  "Cyclically Rotating a Grid",
  "Game of Life",
  "Queens That Can Attack the King",
  "Max Increase to Keep City Skyline",
  "Count Submatrices with Top-Left Element and Sum Less Than k",
  "Find the Minimum Area to Cover All Ones II",
  "Valid Sudoku",
  "Check if Move is Legal",
  "Number of Laser Beams in a Bank",
  "Where Will the Ball Fall",
  "Image Overlap",
  "Minimum Operations to Make a Uni-Value Grid",
  "Equal Row and Column Pairs",
  "Difference Between Ones and Zeros in Row and Column",
  "Diagonal Traverse",
  "Matrix Block Sum",
  "Maximum Sum of an Hourglass",
  "Maximum Matrix Sum",
  "Find the Grid of Region Average",
  // "Spiral Matrix",
  // "Spiral Matrix II",
  // "Replace Elements in an Array",
  "Count the Number of Special Characters II",
  "Reconstruct Original Digits from English",
  // "Integer to Roman",
  "Sort Characters by Frequency",
  // "HTML Entity Parser",
  "Group Anagrams",
  "Find All Lonely Numbers in the Array",
  "First Missing Positive",
  "Find Occurrences of an Element in an Array",
  "Groups of Special Equivalent Strings",
  "Word Subsets",
  "Find the Maximum Number of Elements in Subset",
  "Optimal Partition of String",
  "Custom Sort String",
  "Finding the Users Active Minutes",
  "Convert an Array into a 2D Array with Conditions",
  "Group the People Given the Group Size They Belong To",
  "Evaluate the Bracket Pairs of a String",
  "Minimum Number of Operations to Make Word K-Periodic",
  "Can Convert String in K Moves",
  "Restore the Array from Adjacent Pairs",
  "Tuple with Same Product",
  "Split the Array to Make Coprime Products",
  "4Sum II",
  "Brick Wall",
  "Pairs of Songs with Total Durations Divisible by 60",
  "Alphabet Board Path",
  "Vowel Spellchecker",
  "Bulls and Cows",
  "Card Flipping Game",
  "Maximum Size of a Set After Removals",
  "Minimum Absolute Difference Queries",
  "Check if Array Pairs are Divisible by K",
  "Count Pairs That Form a Complete Day II",
  "Count Number of Bad Pairs",
  "Minimum Seconds to Equalize a Circular Array",
  "Sum of Imbalance Numbers of All Subarrays",
  "Grid Illumination",
  "Maximum Equal Frequency",
  "Rearranging Fruits",
  "Subarray Sum Equals K",
  "Make Sum Divisible by P",
  "Count Number of Bad Pairs",
  "Continuous Subarray Sum",
  "Count of Interesting Subarrays",
  "Sum of Digit Differences of All Pairs",
  "Binary Subarrays with Sum",
  "Number of Wonderful Substrings",
  "Number of Submatrices That Sum to Target",
  "Count Subarrays with Median K",
  "Find All Anagrams in a String",
  "Permutation in String",
  "Check If a String Contains All Binary Codes of Size K",
  "Maximum Number of Vowels in a Substring of Given Length",
  "Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold",
  "Maximum Sum of Distinct Subarrays With Length K",
  "Sliding Subarray Beauty",
  "Maximum Points You Can Obtain from Cards",
  "Sliding Window Median",
  "Maximum Sum of 3 Non-Overlapping Subarrays",
  "Longest Substring Without Repeating Characters",
  "Longest Repeating Character Replacement",
  "Maximum Number of Occurrences of a Substring",
  "Count the Number of Substrings With Dominant Ones",
  "Minimum Window Substring",
  "Substring with Concatenation of All Words",
  "Minimum Size Subarray Sum",
  // "Subarray Product Less Than K",
  "Moving Stones Until Consecutive II",
  // "Count Number of Nice Subarrays",
  // "Number of Subarrays with Bounded Maximum",
  "Maximum Erasure Value",
  "Longest Subarray of 1's After Deleting One Element",
  // "Count the Number of Good Subarrays",
  "Minimum Consecutive Cards to Pick Up",
  "Minimum Operations to Reduce X to Zero",
  "Frequency of the Most Frequent Element",
  // "Subarrays with K Different Integers",
  "Minimum Add to Make Parentheses Valid",
  "Minimum Remove to Make Valid Parentheses",
  "Maximum Nesting Depth of Two Valid Parentheses Strings",
  "Check if a Parentheses String Can Be Valid",
  "Reverse Substrings Between Each Pair of Parentheses",
  "Score of Parentheses",
  "Minimum Insertions to Balance a Parentheses String",
  "Longest Valid Parentheses",
  "Redundant Parenthesis",
  "Maximum Frequency Stack",
  "Design a Stack With Increment Operation",
  "Dinner Plate Stacks",
  "Merge Intervals",
  "Asteroid Collision",
  "Construct Smallest Number From DI String",
  "Evaluate Reverse Polish Notation",
  "Simplify Path",
  "Basic Calculator",
  "Basic Calculator II",
  "Basic Calculator IV",
  "Robot Collisons",
  "Number of atoms",
  "Final Prices With a Special Discount in a Shop",
  "Next Greater Element II",
  "Next Greater Element IV",
  "Daily Temperatures",
  "Car Fleet II",
  "132 Pattern",
  "Smallest Subsequence of Distinct Characters",
  "Count Submatrices With All Ones",
  "Remove Duplicate Letters",
  "The Number of Weak Characters in the Game",
  "Maximum Subarray Min-Product",
  "Sum of Subarray Minimums",
  "Shortest Unsorted Continuous Subarray",
  "Remove K Digits",
  "Beautiful Towers I",
  "Beautiful Towers II",
  "Online Stock Span",
  // "Minimum Number of Increments on Subarrays to Form a Target Array",
  "Maximum Score of a Good Subarray",
  "Number of Visible People in a Queue",
  "Maximal Rectangle",
  "Largest Rectangle in Histogram",
  "Create Maximum Number",
  "Find Building Where Alice And Bob Can Meet",
  "Sum Of Total Strength Of Wizards",
  "First Negative Integer in Every Window of Size K",
  "Find the Winner of the Circular Game",
  "Reveal Cards in Increasing Order",
  "Stamping the Sequence",
  "Design Circular Deque",
  "Jump Game VI",
  "Continuous Subarrays",
  "Max Value of Equation",
  "Sliding Window Maximum",
  "Shortest Subarray with Sum at Least K",
  "Constrained Subsequence Sum",
  "H-Index II",
  "Online Election",
  "Most Beautiful Item for Each Query",
  "Time Based Key-Value Store",
  "Random Pick with Weight",
  "Plates Between Candles",
  "Successful Pairs of Spells and Potions",
  "Range Frequency Queries",
  "Minimum Operations to Make All Array Elements Equal",
  "Count Number of Rectangles Containing Each Point",
  "Count the Number of Fair Pairs",
  "Minimum Absolute Sum Difference",
  "Find the Longest Valid Obstacle Course at Each Position",
  "Find the Number of Subarrays Where Boundary Elements Are Maximum",
  "Search a 2D Matrix",
  "Search a 2D Matrix II",
  "Median in a Row-wise Sorted Matrix",
  // "Single Element in a Sorted Array",
  // "Find the Duplicate Number",
  "Find Peak Element",
  "Find a Peak Element II",
  "Find Minimum in Rotated Sorted Array",
  // "Peak Index in a Mountain Array",
  "Search in Rotated Sorted Array",
  "Search in Rotated Sorted Array II",
  "Rotation",
  "Find Minimum in Rotated Sorted Array II",
  "Koko Eating Bananas",
  "Find the Smallest Divisor Given a Threshold",
  "Minimum Number of Days to Make M Bouquets",
  "Aggressive Cows",
  // "Maximum Candies Allocated to K Children",
  "Most Profit Assigning Work",
  // "Maximum Value at a Given Index in a Bounded Array",
  "Maximum Side Length of a Square With Sum Less Than or Equal to Threshold",
  "Minimum Time to Repair Cars",
  "Maximum Number of Removable Characters",
  "Heaters",
  "Earliest Second to Mark Indices I",
  "Maximum White Tiles Covered by a Carpet",
  "Minimum Absolute Difference Between Elements with Constraint",
  "Ugly Number III",
  "Minimize the Maximum of Two Arrays",
  "Split Array Largest Sum",
  "Maximum Number of Robots Within Budget",
  "Maximum Number of Groups With Increasing Length",
  "Maximum Number of Tasks You Can Assign",
  "Median of Two Sorted Arrays",
  "Magnetic Force Between Two Balls",
  "Maximum Tastiness of Candy Basket",
  "Minimized Maximum of Products Distributed to Any Store",
  "Minimize the Maximum Difference of Pairs",
  "Kth Smallest Number in Multiplication Table",
  "Find the Median of the Uniqueness Array",
  "Kth Smallest Product of Two Sorted Arrays",
  "Kth Smallest Amount With Single Denomination Combination",
  "Find the Kth Smallest Sum of a Matrix With Sorted Rows",
  "Pow(x, n)",
  "Minimum Non-Zero Product of the Array Elements",
  "Sort a Stack",
  "Find the Winner of the Circular Game",
  "Predict the Winner",
  "Tower of Hanoi",
  "Different Ways to Add Parentheses",
  "Basic Calculator",
  "Regular Expression Matching",
  "Wildcard Matching",
  "Integer to English Words",
  "Special Binary String",
  "Permutations",
  "Construct Smallest Number from DI String",
  "Target Sum",
  "Combinations",
  "Letter Combinations of a Phone Number",
  "Letter Case Permutation",
  "K-th Lexicographical String of All Happy Strings of Length n",
  "Combination Sum",
  "Combination Sum II",
  "Combination Sum III",
  "Maximum Compatibility Score Sum",
  "Numbers with Same Consecutive Differences",
  "N-Queens",
  "Subsets",
  "Subsets II",
  "Non-Decreasing Subsequences",
  "Number of Beautiful Subsets",
  "Rat in a Maze Problem",
  "Sudoku Solver",
  // "Check Completeness of a Binary Tree",
  "Construct Binary Tree from Parent Array",
  "Linked List to Binary Tree",
  "Construct Binary Tree from Preorder and Inorder Traversal",
  "Construct Binary Tree from Inorder and Postorder Traversal",
  "Construct Binary Tree from Preorder and Postorder Traversal",
  "Construct Binary Tree from String with Bracket Representation",
  "Check if Subtree",
  "Mirror Tree",
  "Binary Tree Level Order Traversal",
  "Binary Tree Level Order Traversal II",
  "Minimum Number of Operations to Sort a Binary Tree by Level",
  "Top View of Binary Tree",
  "Serialize and Deserialize Binary Tree",
  "All Nodes Distance K in Binary Tree",
  "Burning Tree",
  "Populating Next Right Pointers in Each Node",
  "Path Sum II",
  "Sum Root to Leaf Numbers",
  "Binary Tree Maximum Path Sum",
  "Path Sum III",
  "Lowest Common Ancestor of a Binary Tree",
  "Insert into a Binary Search Tree",
  "Delete Node in a BST",
  "Convert Sorted List to Binary Search Tree",
  "Convert BST to Greater Tree",
  "Serialize and Deserialize BST",
  "Construct Binary Search Tree from Preorder Traversal",
  "Construct BST from Postorder",
  "Balance a Binary Search Tree",
  "Binary Search Tree to Greater Sum Tree",
  "Validate Binary Search Tree",
  "Kth Smallest Element in a BST",
  "Maximum Sum BST in Binary Tree",
  "Find Common Nodes in two BSTs",
  "All Elements in Two Binary Search Trees",
  "Unique Binary Search Trees",
  "Recover Binary Search Tree",
  "Binary Search Tree Iterator",
  "Lowest Common Ancestor of a Binary Search Tree",
  "Heap Sort",
  "Is Binary Tree Heap?",
  "Operations on Binary Min Heap",
  "Convert Min Heap to Max Heap",
  "Seat Reservation Manager",
  "Sort Characters By Frequency",
  "Longest Happy String",
  "Maximum Average Pass Ratio",
  "Find Score of an Array After Marking All Elements",
  "Furthest Building You Can Reach",
  "Distant Barcodes",
  "Task Scheduler",
  "Maximal Score After Applying K Operations",
  "Single Threaded CPU",
  "Most Popular Video Creator",
  "Total Cost to Hire K Workers",
  "Process Tasks Using Servers",
  "Maximum Number of Eaten Apples",
  "Maximum Number of Events That Can Be Attended",
  "Minimum Operations to Exceed Threshold Value II",
  "Put Marbles in Bags",
  "Maximum Spending After Buying Items",
  "Trapping Rain Water II",
  "Maximum Performance of a Team",
  "Max Value of Equation",
  "The Skyline Problem",
  "Maximum Elegance of a K-Length Subsequence",
  "Kth Largest Element in an Array",
  "K Closest Points to Origin",
  "Kth Smallest Element in a Sorted Matrix",
  "Find Kth Largest XOR Coordinate Value",
  "Top K Frequent Words",
  "Find K Closest Elements",
  "Ugly Number II",
  "Find the Kth Largest Integer in the Array",
  "Reward Top K Students",
  "Query Kth Smallest Trimmed Number",
  "K Highest Ranked Items Within a Price Range",
  "Find the Kth Smallest Sum of a Matrix With Sorted Rows",
  "Find the K-Sum of an Array",
  "Remove Stones to Minimize the Total",
  "Minimum Operations to Halve Array Sum",
  "The Number of the Smallest Unoccupied Chair",
  "Lexicographically Minimum String After Removing Stars",
  "Replace Question Marks in String to Minimize Its Value",
  "Minimum Cost to Hire K Workers",
  "Minimize Deviation in Array",
  "Minimum Moves to Move a Box to Their Target Location",
  "Minimum Interval to Include Each Query",
  "Find K Pairs with Smallest Sums",
  "Merge K Sorted Arrays",
  "Number of Orders in the Backlog",
  "Sliding Window Median",
  "IPO",
  "Meeting Rooms III",
  "Time to Cross a Bridge",
  "Trie Delete",
  "Design Add and Search Words Data Structure",
  "Map Sum Pairs",
  "Longest Common Prefix",
  "Find the Length of the Longest Common Prefix",
  "Search Suggestions System",
  "Longest Common Suffix Queries",
  "Implement Magic Dictionary",
  "Number of Matching Subsequences",
  "Camelcase Matching",
  "Encrypt and Decrypt Strings",
  "Longest Word in Dictionary",
  "Construct String With Minimum Cost",
  // "Shortest Uncommon Substring in an Array",
  "Word Break",
  "Word Break II",
  "Word Search II",
  "Palindrome Pairs",
  "Remove Sub-Folders from the Filesystem",
  "Delete Duplicate Folders in System",
  "Jump Game",
  "Jump Game II",
  // "Wiggle Subsequence",
  "Cinema Seat Allocation",
  "Advantage Shuffle",
  "Minimum Score by Changing Two Elements",
  "Minimum Operations to Make Array Equal II",
  "Mice and Cheese",
  "Minimum Seconds to Equalize a Circular Array",
  // "Maximum Bags with Full Capacity of Rocks",
  "Minimize Maximum of Array",
  "Minimum Platforms",
  "Fractional Knapsack",
  "Activity Selection",
  "Job Sequencing Problem",
  "Non-Overlapping Intervals",
  "Divide Intervals into Minimum Number of Groups",
  "Task Scheduler",
  "Minimum Number of Operations to Make Arrays Similar",
  "Patching Array",
  "Reverse Subarray to Maximize Array Value",
  "Super Washing Machines",
  "Minimum Cost to Equalize Array",
  "Optimal Partition of String",
  "Minimum Swaps to Make Strings Equal",
  "Maximum Number of Non-Overlapping Substrings",
  "Lexicographically Smallest Beautiful String",
  "Count K-Subsequences of a String with Maximum Beauty",
  "Bag of Tokens",
  "Boats to Save People",
  "Maximum Matching of Players with Trainers",
  "Candy",
  "Gas Station",
  "Group the People Given the Group Size They Belong To",
  // "Previous Permutation with One Swap",
  "Partition Labels",
  "Construct K Palindrome Strings",
  "Reorganize String",
  "String Without AAA or BBB",
  // "Check If a String Can Break Another String",
  "Remove Duplicate Letters",
  "Lexicographically Smallest String After Substring Operation",
  "Minimum Rounds to Complete All Tasks",
  "Number of Burgers with No Waste of Ingredients",
  "Queue Reconstruction by Height",
  "Perfect Squares",
  "Decode Ways",
  "Unique Binary Search Trees",
  "House Robber",
  "Coin Change",
  "Minimum Cost For Tickets",
  "Delete and Earn",
  "Maximum Total Damage With Spell Casting",
  "Arithmetic Slices",
  "Partition Array for Maximum Sum",
  "Maximize Consecutive Elements in an Array After Modification",
  "Coin Change II",
  "Knight Dialer",
  "Partition Equal Subset Sum",
  "Triangle",
  "Student Attendance Record Leetcode",
  "Find the Maximum Length of a Good Subsequence II",
  "K Inverse Pairs Array",
  "Combination Sum IV",
  "Largest Sum of Averages",
  "Longest Arithmetic Subsequence",
  "Number of Dice Rolls With Target Sum",
  "Dice Roll Simulation",
  "Number of Strings Which Can Be Rearranged to Contain Substring",
  "Frog Jump",
  "Best Time to Buy and Sell Stock II",
  "Best Time to Buy and Sell Stock III",
  "Best Time to Buy and Sell Stock IV",
  "Number of Music Playlists",
  "Count Vowels Permutation",
  "Best Time to Buy and Sell Stock with Transaction Fee",
  "Minimum Distance to Type a Word Using Two Fingers",
  "Best Time to Buy and Sell Stock with Cooldown",
  "Number of Ways to Paint N × 3 Grid",
  "Build Array Where You Can Find The Maximum Exactly K Comparisons",
  "Number of Ways of Cutting a Pizza",
  "Paint House III",
  "Count All Possible Routes",
  "Geek's Training",
  // "Unique Paths",
  // "Unique Paths II",
  "Minimum Path Sum",
  "Maximum Non Negative Product in a Matrix",
  "Maximum Difference Score in a Grid",
  "Minimum Number of Operations to Satisfy Conditions",
  "Maximum Number of Moves in a Grid",
  "Where Will the Ball Fall",
  "Dungeon Game",
  "Cherry Pickup",
  "Number of Paths with Max Score",
  "Cherry Pickup II",
  "Minimum Falling Path Sum II",
  "Out of Boundary Paths",
  "Minimum Falling Path Sum",
  "Knapsack - 1",
  "Knapsack - 2",
  "Ones and Zeroes",
  "Target Sum",
  "2 Keys Keyboard",
  "Best Team With No Conflicts",
  "Shopping Offers",
  "Minimum Number of Coins for Fruits",
  "Last Stone Weight II",
  "Rod Cutting",
  "Filling Bookcase Shelves",
  "Video Stitching",
  "Pizza With 3n Slices",
  "Minimum Swaps To Make Sequences Increasing",
  "Profitable Schemes",
  "Reducing Dishes",
  "Find Number of Ways to Reach the K-th Stair",
  "Find the Sum of Subsequence Powers",
  "Count of Sub-Multisets With Bounded Sum",
  "Longest Increasing Subsequence",
  "Printing Longest Increasing Subsequence",
  // "Number of Longest Increasing Subsequence",
  "Largest Divisible Subset",
  "Longest Unequal Adjacent Groups Subsequence II",
  "Max Sum Increasing Subsequence",
  "Find the Maximum Length of Valid Subsequence II",
  "Wiggle Subsequence",
  // "Find the Count of Monotonic Pairs I",
  "Russian Doll Envelopes",
  "Delete Columns to Make Sorted III",
  "Minimum Number of Removals to Make Mountain Array",
  "Maximum Height by Stacking Cuboids",
  // "Maximum Length of Pair Chain",
  "Make Array Strictly Increasing",
  "Print all LCS sequences",
  "Count Common Subsequence in Two Strings",
  "Theory",
  "Delete operation for two strings",
  "Longest Palindromic Substring",
  "Edit Distance",
  "Interleaving String",
  "Regular Expression Matching",
  "Wildcard Matching",
  "Shortest Common Supersequence",
  "Minimum Insertion Steps to Make a String Palindrome",
  // "Max Dot Product of Two Subsequences",
  "Minimum Substring Partition of Equal Character Frequency",
  "Apply Operations to Make Two Strings Equal",
  "Minimum ASCII Delete Sum for Two Strings",
  "Word Break",
  "Unique Substrings in Wraparound String",
  "Longest Valid Parentheses",
  "Distinct Subsequences",
  "Word Break II",
  "Sort an Array",
  "Concatenated Words",
  "Count Different Palindromic Subsequences",
  "Distinct Subsequences II",
  "Longest Chunked Palindrome Decomposition",
  "Minimum Changes to Make K Semi-palindromes",
  "Maximal Square",
  "Largest Plus Sign",
  "Largest 1-Bordered Square",
  // "Count Square Submatrices with All Ones",
  "Matrix Block Sum",
  "Count Submatrices With All Ones",
  "Ways to Make a Fair Array",
  "Maximal Rectangle",
  "Max Sum of Rectangle No Larger Than K",
  "Super Washing Machines",
  "Maximum Sum of 3 Non-Overlapping Subarrays",
  "Number of Submatrices That Sum to Target",
  "Find the Count of Monotonic Pairs II",
  "Get the Maximum Score",
  "Matrix Chain Multiplication",
  "Guess Number Higher or Lower II",
  "Predict the Winner",
  "Stone Game",
  "Burst Balloons",
  "Minimum Cost Tree From Leaf Values",
  "Partition Array for Maximum Sum",
  "Palindrome Partitioning II",
  "Stone Game VII",
  "Strange Printer",
  "Valid Permutations for DI Sequence",
  "Minimum Cost to Merge Stones",
  "Allocate Mailboxes",
  "Minimum Cost to Cut a Stick",
  "Stone Game V",
  "Palindrome Partitioning III",
  "Maximum Subarray",
  "Maximum Product Subarray",
  "Bitwise ORs of Subarrays",
  "Longest Turbulent Subarray",
  "Maximum Subarray Sum with One Deletion",
  "K-Concatenation Maximum Sum",
  "Length of Longest Fibonacci Subsequence",
  "Keys and Rooms",
  "Number of Provinces",
  // "Count the Number of Complete Components",
  "Reorder Routes to Make All Paths Lead to the City Zero",
  "Longest Cycle in a Graph",
  "Snakes and Ladders",
  "Round Trip",
  "Word Ladder",
  "Valid BFS?",
  "Count the Number of Houses at a Certain Distance I",
  // "As Far from Land as Possible",
  "Minimum Operations to Convert Number",
  "Shortest Path with Alternating Colors",
  "Minimum Number of Operations to Make X and Y Equal",
  "Shortest Path Visiting All Nodes",
  "Jump Game III",
  // "Clone Graph",
  "Last Day Where You Can Still Cross",
  "Sliding Puzzle",
  "Maximum Candies You Can Get from Boxes",
  "Shortest Path to Get All Keys",
  "Jump Game IV",
  "Word Ladder II",
  "Escape the Spreading Fire",
  "Detect Cycle in an Undirected Graph (GeeksforGeeks)",
  "Detect Cycle in a Directed Graph (GeeksforGeeks)",
  "Check if a Graph Has a Cycle of Odd Length",
  "Detect Cycles in 2D Grid",
  "Shortest Cycle in a Graph",
  "Is Graph Bipartite?",
  "Possible Bipartition",
  // "Flower Planting With No Adjacent",
  "Divide Nodes into the Maximum Number of Groups",
  "Course Schedule",
  "Course Schedule II",
  "Find Eventual Safe States",
  "Minimum Height Trees",
  "Loud and Rich",
  "All Ancestors of a Node in a Directed Acyclic Graph",
  "Find All Possible Recipes from Given Supplies",
  "Alien Dictionary",
  // "Longest Increasing Path in a Matrix",
  "Cat and Mouse",
  "Sort Items by Groups Respecting Dependencies",
  "Sort Items by Groups Respecting Dependencies",
  "Largest Color Value in a Directed Graph",
  "Parallel Courses III",
  "Parallel Courses II",
  "Number of Increasing Paths in a Grid",
  "Build a Matrix With Conditions",
  "Battleships in a Board",
  "Max Area of Island",
  "Count Sub Islands",
  "Find All Groups of Farmland",
  "Rotting Oranges",
  "Number of Enclaves",
  "Map of Highest Peak",
  "Surrounded Regions",
  "01 Matrix",
  "Shortest Bridge",
  "Shortest Route I",
  "Investigation",
  "Flight Discount",
  "Cheapest Flights Within K Stops",
  "Number of Ways to Arrive at Destination",
  "Path with Maximum Probability",
  // "Path with Minimum Effort",
  "Number of Restricted Paths from First to Last Node",
  "Reachable Nodes in Subdivided Graph",
  "Minimum Cost to Make at Least One Valid Path in a Grid",
  // "Minimum Obstacle Removal to Reach Corner",
  // "Shortest Path in Binary Matrix",
  "Nearest Exit from Entrance in Maze",
  "Minimum Cost to Make at Least One Valid Path in a Grid",
  "Second Minimum Time to Reach Destination",
  "High Score",
  "Cycle Finding",
  "Bus Routes",
  "Road Construction",
  "Course Schedule IV",
  "Find the City With the Smallest Number of Neighbors at a Threshold Distance",
  "Count the Number of Houses at a Certain Distance I",
  "Minimum Cost to Convert String I",
  "Greg and Array",
  "Design Graph With Shortest Path Calculator",
  "Number of Possible Sets of Closing Branches",
  "Find the Shortest Superstring",
  "Redundant Connection",
  "Smallest String With Swaps",
  "Accounts Merge",
  "Most Stones Removed with Same Row or Column",
  "Find Latest Group of Size M",
  "Redundant Connection II",
  "Making a Large Island",
  "GCD Sort of an Array",
  "Bricks Falling When Hit",
  "Checking Existence of Edge Length Limited Paths",
  "Remove Max Number of Edges to Keep Graph Fully Traversable",
  "Rank Transform of a Matrix",
  "Prim’s Minimum Spanning Tree (MST) – Greedy Algorithm",
  "Theory",
  "Kruskal’s Minimum Spanning Tree Algorithm – Greedy Algorithm",
  "Theory",
  "Min Cost to Connect All Points",
  "Water Connection Problem",
  "Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree",
  "Remove Max Number of Edges to Keep Graph Fully Traversable",
];

const notDone = [
  "Max Value of Equation",
  "Length of Longest Fibonacci Subsequence",
  "Shortest Impossible Sequence of Rolls",
  "Remove Boxes",
  "Find the City With the Smallest Number of Neighbors at a Threshold Distance",
  "Number of Subarrays with Bounded Maximum",
  "Minimum Cost to Cut the Stick", 
  "Delete Columns to Make Sorted III",
  "Sum of Imbalance Numbers of All Subarrays",
  "Minimum Number of K Consecutive Bit Flips",
  "Longest Arithmetic Subsequence",
  "Maximum White Tiles Covered by a Carpet", 
  "Freedom Trail",
  "Delete Columns to Make Sorted III",
  "Sum of Imbalance Numbers of All Subarrays",
  "Maximum White Tiles Covered by a Carpet",
  "H-Index",
  "Minimum Number of Operations to Make Arrays Similar",
  "Flower Planting With No Adjacent",
  "http://leetcode.com/problems/minimum-number-of-k-consecutive-bit-flips/description/",
  "Longest Arithmetic Subsequence",
  "Maximum White Tiles Covered by a Carpet",
  "Maximize the Minimum Powered City",
];

function getRandomTitle(titles) {
  if (!Array.isArray(titles) || titles.length === 0) return null;
  const randomIndex = Math.floor(Math.random() * titles.length);
  return titles[randomIndex];
}

//do next Minimum Swaps To Make Sequences Increasing

//data2 have 795 count

console.log(data.length);
console.log(getRandomTitle(data));