const data1 = [
  "What is C++?",
  "Literals",
  "Comments",
  "Variables",
  "Data Types",
  "Print Output",
  "Operators Part 1",
  "Operators Part 2",
  "Booleans",
  "If-Else",
  "Else-If Ladder",
  "While Loop",
  "For Loop",
  "Loops Standard Problems",
  "Break and Continue",
  "Switch Statement",
  "Functions",
  "Functions Arguments",
  "Return Statement",
  "Local Variable",
  "Why Do We Use Arguments and Return Type in a Function?",
  "Standard Library Functions",
  "Nested Functions",
  "Arrays",
  "Iterating and Updating Arrays",
  "Taking Input in Arrays",
  "Arrays Memory Allocation",
  "Caveats in C++ Arrays",
  "Quiz: Arrays Theory",
  "Ranged For Loops",
  "Arrays and Functions",
  "Passing Array in Functions",
  "Strings",
  "Taking Input in Strings",
  "String vs Arrays",
  "Basic Functions of String",
  "Vector Basics",
  "Vector Implementation - 1",
  "Vector Implementation - 2",
  "Quiz: Vectors",
  "Multi-dimensional arrays in C++",
  "What is Java?",
  "Features of Java",
  "Java vs C++",
  "JVM, JRE, and JDK",
  "First Program in Java",
  "Comments and Statements",
  "Literals in Java",
  "Variables in Java",
  "How to Print in Java?",
  "Data Types in Java",
  "Operators in Java",
  "Arithmetic Operators in Java",
  "Multiple Operators in Java",
  "Type Conversion in Java",
  "User Input in Java",
  "Making Logical Decisions in Programming: Comparing Values and Variables",
  "If-Else Statement in Java",
  "While Loop in Java",
  "For Loop in Java",
  "Do-While Loop",
  "Standard Practice Problems in Java",
  "Break and Continue in Java",
  "Switch Statement in Java",
  "Arrays in Java",
  "Types of Array in Java",
  "Iterating Through Arrays",
  "Arrays: Practice Problems I",
  "Arrays: Practice Problems II",
  "Arrays: Practice Problems III",
  "Arrays: Practice Problems IV",
  "Methods in Java",
  "Method Arguments in Java",
  "Why Do We Use Arguments and Return Type in a Method?",
  "Standard Library Methods",
  "Local Variables in a Method",
  "Why, What and How?",
  "Popular Online Platforms",
  "Tearing Down a Problem",
  "Inroduction to Time Complexity",
  "Introduction to Space Complexity",
  "Different Notations in Time Complexity",
  "Comparing different time complexities",
  "How to Calculate Time Complexity?",
  "Quiz: Time Complexity",
  "if-else and else-if ladder Practice",
  "Loops Practice 1",
  "Loops Practice 2",
  "Loops Practice 3",
  "Loops Practice 4",
  "Square Star and Rhombus Star Patterns",
  "Triangle Star Patterns",
  "Pyramid Star Patterns",
  "Miscellaneous Star Patterns",
  "Number Patterns 1",
  "Number Patterns 2",
  "Triangular Number Patterns 1",
  "Triangular Number Patterns 2",
  "Triangular Number Patterns 3",
  "Switch Statement Practice",
  "Print Each Element and Its Index in an Array",
  "Print Elements of an Array in Reverse Order",
  "Print Alternate Elements of an Array",
  "Create a Duplicate of an Array",
  "Create Two Arrays one for Odd Elements and one for Even Elements",
  "Calculate Sum and Product of Array Elements",
  "Count Occurrences of a Target Number in an Array",
  "Check if an Array is Sorted Forward, Backward or Not at All",
  "Count Unique and Duplicate Elements in an Array",
  "Check if Two Elements Exist with a Sum Equal to a Target Value",
  "Check if Three Elements Exist with a Sum Equal to a Target Value",
  "Find the Maximum Element in an Array",
  "Find the Minimum Element in an Array",
  "Find the Second Maximum Element; if None, Print -1",
  "Find the Second Minimum Element; if None, Print -1",
  "Insert an Element at the Xth Position, Shifting Right",
  "Delete an Element at the Xth Position, Shifting Left",
  "Print ASCII Value of Each Character in a String",
  "Count Letters, Numbers, and Special Characters in a String",
  "Find the Difference between the Number of Consonants and Vowels",
  "Convert Uppercase to Lowercase and Vice Versa in a String",
  "Remove Leading, Trailing, and Extra Spaces in a String",
  "Count the Number of Words in a String",
  "Find the Maximum and Minimum Occurring Characters in a String",
  "Check if There are Two or Three Consecutive Identical Characters in a String",
  "Find the First and Last Index of Occurrence for Each Character in a String",
  "Check if a String Contains All Letters from 'a' to 'z'",
  "Insert a Character at the First, Last, and Kth Position in a String",
  "Remove the First, Last, and Kth Character from a String",
  "Find a Specific Substring within a String",
  "Generate All Possible Substrings of a String",
  "Print a Matrix Row-Wise and Column-Wise",
  "Calculate the Total Sum of Elements in a Matrix",
  "Calculate the Sum of Each Row and Each Column in a Matrix",
  "Find the Maximum and Minimum Values in Each Row of a Matrix",
  "Find the Maximum and Minimum Values in Each Column of a Matrix",
  "Add and Subtract Two Matrices",
  "Print the Upper Triangle and Lower Triangle of a Matrix",
  "Print the Left and Right Diagonals of a Matrix",
  "Print the Boundary Elements of a Matrix",
  "Sort the Matrix Row-Wise and Column-Wise",
  "Print the Matrix in a Zig-Zag Pattern",
  "Check if a Matrix is Symmetric",
  "Check if a Matrix is an Identity Matrix",
  "Check if a Matrix is Sparse (Mostly Zeroes)",
  "Find the Inverse of a Matrix",
  "Perform Basic Operations (Addition, Subtraction, Multiplication, Division) using Two Numbers",
  "Find the Sum of Digits of a Number",
  "Reverse a Given Number",
  "Check if a Number is a Palindrome",
  "Check if a Number is an Armstrong Number",
  "Count the Total Occurrences of the Digit '1' in All Positive Integers Less than or Equal to a Given Integer n",
  "Generate Fibonacci Numbers up to a Given Limit",
  "Calculate the Factorial of a Number",
  "Find the Number of Trailing Zeroes in the Factorial of a Given Number n",
  "Calculate the LCM and GCD of Two Numbers",
  "Check if a Number is Prime without using the Sieve of Eratosthenes",
  "Check if Two Numbers are Co-Prime",
  "Find All Divisors of a Given Number",
  "Perform Modulo Operations",
  "Check Divisibility Rules for Numbers from 1 to 20",
  "Introduction to Recursion",
  "Getting a hang of Recursion",
  "Some simple problems using Recursion",
  "Fast Exponentiation",
  "Power of Three",
  "Recursion: Time & Space Complexity Analysis - 1",
  "Recursion: Time & Space Complexity Analysis - 2",
  "Time Complexity Analysis using Recurrence Relations",
  "Calculate the Sum of Numbers from 1 to N using Recursion",
  "Print the Fibonacci Series up to N Terms using Recursion",
  "Print the Elements of an Array using Recursion",
  "Count the Digits of a Given Number using Recursion",
  "Find the Sum of Digits of a Number using Recursion",
  "Find the GCD of Two Numbers using Recursion",
  "Find the Largest Element of an Array using Recursion",
  "Reverse a String using Recursion",
  "Find the Factorial of a Number using Recursion",
  "Convert a Decimal Number to Binary using Recursion",
  "Check if a Number is a Prime Number using Recursion",
  "Print Even or Odd Numbers in a Given Range using Recursion",
  "Multiply Two Matrices using Recursion",
  "Check if a Given String is a Palindrome using Recursion",
  "Copy One String to Another using Recursion",
  "Check if an Array is Sorted using Recursion",
  "Bubble Sort",
  "Insertion Sort Algorithm",
  "Insertion Sort List ",
  "Selection Sort Algorithm",
  "Merge Sort",
  "Count Inversions",
  "Count of Smaller Numbers After Self",
  "Count of Range Sum",
  "Reverse Pairs",
  "Create Sorted Array through Instructions",
  "Count Good Triplets in an Array",
  "Number of Pairs Satisfying Inequality",
  "Quick Sort",
  "Sort an Array",
  "Counting Sort",
  "Relative Sort Array",
  "Reduce Array Size to The Half",
  "Maximum Ice Cream Bars",
  "Radix Sort",
  "Bucket Sort",
  "Top K Frequent Elements",
  "Sort Characters By Frequency",
  "Maximum Gap",
  "Top K Frequent Words",
  "Contains Duplicate III",
  "First Missing Positive",
  "Missing Number",
  "Find the Duplicate Number",
  "Comparator Sort",
  "Custom Sort String",
  "Largest Number",
  "Sort the Jumbled Numbers",
  "Rank Teams by Votes",
  "Merge Two 2D Arrays by Summing Values",
  "Merge Sorted Array",
  "Sort Array by Parity",
  "Sort Array by Parity II",
  "Rearrange Array Elements by Sign",
  "Remove Duplicates from Sorted Array",
  "Remove Element",
  "Partition Array According to Given Pivot",
  "Rotate Array",
  "Apply Operations to an Array",
  "Find All K-Distant Indices in an Array",
  "Two Sum",
  "3Sum",
  "3Sum Closest",
  "4Sum",
  "Sort Colors",
  "Container With Most Water",
  "Watering Plants II",
  "Next Permutation",
  "Next Greater Element III",
  "Reverse String",
  "Reverse Prefix of Word",
  "Reverse Vowels of a String",
  "Reverse Words in a String",
  "Reverse Words in a String III",
  "Valid Palindrome",
  "Valid Palindrome II",
  "Lexicographically Smallest Palindrome",
  "Merge Strings Alternately",
  "Largest Merge of Two Strings",
  "Shortest Distance to a Character",
  "DI String Match",
  "Make String a Subsequence Using Cyclic Increments",
  "Count Binary Substrings",
  "Minimum Length of String After Deleting Similar Ends",
  "String Compression",
  "Separate Black and White Balls",
  "Move Pieces to Obtain a String",
  "Sentence Similarity III",
  "Range Sum Query - Immutable",
  "Left and Right Sum Differences ",
  "Count Vowel Strings in Ranges",
  "Minimum Penalty for a Shop",
  "Find Good Days to Rob the Bank",
  "Sum of Absolute Differences in a Sorted Array",
  "Product of Array Except Self",
  "Product of the Last K Numbers",
  "Removing Minimum Number of Magic Beans",
  "Find All Good Indices",
  "Movement of Robots",
  "Range Sum Query 2D - Immutable",
  "Increment Submatrices by One",
  "Power of Heroes",
  "Minimum Cost to Make Array Equal",
  "Maximum Population Year",
  "Points That Intersect With Cars",
  "Pongal Bunk",
  "Car Pooling",
  "My Calendar II",
  "Shifting Letters II",
  "Perfect Rectangle",
  "Rectangle Area II",
  "Number of Flowers in Full Bloom",
  "Convert 1D Array Into 2D Array",
  "Modify the Matrix",
  "Set Matrix Zeroes",
  "Sort the Matrix Diagonally",
  "Minimum Operations to Write the Letter Y on a Grid",
  "Shift 2D Grid",
  "Matrix Similarity After Cyclic Shifts",
  "Transpose Matrix",
  "Rotate Image",
  "Rotating the Box",
  "Cyclically Rotating a Grid",
  "Game of Life",
  "Matrix Cells in Distance Order",
  "Find Valid Matrix Given Row and Column Sums",
  "Check if Matrix is X-Matrix",
  "Queens That Can Attack the King",
  "Max Increase to Keep City Skyline",
  "Make a Square with the Same Color",
  "Subrectangle Queries",
  "Count Submatrices with Top-Left Element and Sum Less Than k",
  "Find the Minimum Area to Cover All Ones I",
  "Find the Minimum Area to Cover All Ones II",
  "Valid Sudoku",
  "Check if Move is Legal",
  "Valid Tic-Tac-Toe State",
  "Number of Laser Beams in a Bank",
  "Where Will the Ball Fall",
  "Image Overlap",
  "Minimum Operations to Make a Uni-Value Grid",
  "Row With Maximum Ones",
  "Richest Customer Wealth",
  "Lucky Numbers in a Matrix",
  "Equal Row and Column Pairs",
  "Difference Between Ones and Zeros in Row and Column",
  "Matrix Diagonal Sum",
  "Prime in Diagonal",
  "Diagonal Traverse",
  "Matrix Block Sum",
  "Largest Local Values in a Matrix",
  "Maximum Sum of an Hourglass",
  "Maximum Matrix Sum",
  "Find the Grid of Region Average",
  "Spiral Matrix",
  "Spiral Matrix II",
  "Find Common Elements Between Two Arrays",
  "Contains Duplicate",
  "Sum of Unique Elements",
  "Find All Duplicates in an Array",
  "Check if All Characters Have Equal Number of Occurrences",
  "Unique Number of Occurrences",
  "Find Common Characters",
  "Number of Good Pairs",
  "Permutation Difference Between Two Strings",
  "Check if the Sentence is Pangram",
  "Decode the Message",
  "Replace Elements in an Array",
  "Count the Number of Special Characters II",
  "Reconstruct Original Digits from English",
  "Integer to Roman",
  "Find Words That Can Be Formed by Characters",
  "Find the XOR of Numbers Which Appear Twice",
  "Sort the People",
  "Form Smallest Number from Two-Digit Arrays",
  "Increasing Decreasing String",
  "Sort Array by Increasing Frequency",
  "Sort Characters by Frequency",
  "Merge Similar Items",
  "Substrings of Size Three with Distinct Characters",
  "Clear Digits",
  "HTML Entity Parser",
  "Largest Substring Between Two Equal Characters",
  "Remove Letter to Equalize Frequency",
  "Distribute Candies",
  "Path Crossing",
  "Buddy Strings",
  "Word Pattern",
  "Valid Anagram",
  "Find Resultant Array After Removing Anagrams",
  "Group Anagrams",
  "Majority Element",
  "Majority Element II",
  "Find All Lonely Numbers in the Array",
  "Smallest Missing Integer Greater Than Sequential Prefix Sum",
  "First Missing Positive",
  "Shortest Impossible Sequence of Rolls",
  "Find Occurrences of an Element in an Array",
  "Redistribute Characters to Make All Strings Equal",
  "Isomorphic Strings",
  "Groups of Special Equivalent Strings",
  "Word Subsets",
  "Find the Maximum Number of Elements in Subset",
  "People Whose List of Favorite Companies is Not a Subset of Another List",
  "Count the Number of Good Partitions",
  "Optimal Partition of String",
  "Custom Sort String",
  "Finding the Users Active Minutes",
  "Convert an Array into a 2D Array with Conditions",
  "Group the People Given the Group Size They Belong To",
  "Evaluate the Bracket Pairs of a String",
  "Minimum Number of Operations to Make Word K-Periodic",
  "Can Convert String in K Moves",
  "Restore the Array from Adjacent Pairs",
  "Tuple with Same Product",
  "Split the Array to Make Coprime Products",
  "4Sum II",
  "Count Artifacts That Can Be Extracted",
  "Brick Wall",
  "Pairs of Songs with Total Durations Divisible by 60",
  "Alphabet Board Path",
  "Vowel Spellchecker",
  "Bulls and Cows",
  "Card Flipping Game",
  "Maximum Size of a Set After Removals",
  "Minimum Absolute Difference Queries",
  "Check if Array Pairs are Divisible by K",
  "Count Pairs That Form a Complete Day II",
  "Count Number of Bad Pairs",
  "Minimum Seconds to Equalize a Circular Array",
  "Sum of Imbalance Numbers of All Subarrays",
  "Grid Illumination",
  "Maximum Equal Frequency",
  "Rearranging Fruits",
  "Subarray Sum Equals K",
  "Subarray Sums Divisible by K",
  "Make Sum Divisible by P",
  "Count Number of Bad Pairs",
  "Continuous Subarray Sum",
  "Count of Interesting Subarrays",
  "Count Number of Nice Subarrays",
  "Count Beautiful Substrings II",
  "Sum of Digit Differences of All Pairs",
  "Binary Subarrays with Sum",
  "Number of Wonderful Substrings",
  "Count the Number of Beautiful Subarrays",
  "Number of Submatrices That Sum to Target",
  "Count Subarrays with Median K",
  "Substrings of Size Three with Distinct Characters",
  "Find All Anagrams in a String",
  "Permutation in String",
  "Check If a String Contains All Binary Codes of Size K",
  "Maximum Number of Vowels in a Substring of Given Length",
  "Maximum Average Subarray I",
  "Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold",
  "K Radius Subarray Averages",
  "Maximum Sum of Distinct Subarrays With Length K",
  "Sliding Subarray Beauty",
  "Maximum Points You Can Obtain from Cards",
  "Sliding Window Median",
  "Sliding Window Maximum",
  "Max Value of Equation",
  "Maximum Sum of 3 Non-Overlapping Subarrays",
  "Longest Substring Without Repeating Characters",
  "Longest Repeating Character Replacement",
  "Maximum Number of Occurrences of a Substring",
  "Max Consecutive Ones III",
  "Count the Number of Substrings With Dominant Ones",
  "Minimum Window Substring",
  "Substring with Concatenation of All Words",
  "Minimum Size Subarray Sum",
  "Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit",
  "Fruit Into Baskets",
  "Subarray Product Less Than K",
  "Grumpy Bookstore Owner",
  "Moving Stones Until Consecutive II",
  "Count Number of Nice Subarrays",
  "Number of Subarrays with Bounded Maximum",
  "Maximum Erasure Value",
  "Longest Subarray of 1's After Deleting One Element",
  "Count the Number of Good Subarrays",
  "Minimum Consecutive Cards to Pick Up",
  "Minimum Operations to Reduce X to Zero",
  "Frequency of the Most Frequent Element",
  "Subarrays with K Different Integers",
  "Convert Binary Number in a Linked List to Integer",
  "Intersection of Two Linked Lists",
  "Middle of the Linked List",
  "Linked List Cycle",
  "Linked List Cycle II",
  "Find Length of Loop",
  "Reverse Linked List",
  "Palindrome Linked List",
  "Reverse Nodes in k-Group",
  "Odd Even Linked List",
  "Remove Duplicates from Sorted List",
  "Remove Nth Node From End of List",
  "Delete the Middle Node of a Linked List",
  "Add 1 to a Linked List Number",
  "Add Two Numbers",
  "Sort a Linked List of 0s, 1s, and 2s",
  "Sort List",
  "Linked List Random Node",
  "Copy List with Random Pointer",
  "Flattening a Linked List",
  "Merge Two Sorted Lists",
  "Merge k Sorted Lists",
  "Design HashSet",
  "Design HashMap",
  "Design Browser History",
  "Design a Text Editor",
  "All O'one Data Structure",
  "LRU Cache",
  "LFU Cache",
  "Valid Parentheses",
  "Maximum Nesting Depth of the Parentheses",
  "Remove Outermost Parentheses",
  "Minimum Add to Make Parentheses Valid",
  "Minimum Remove to Make Valid Parentheses",
  "Maximum Nesting Depth of Two Valid Parentheses Strings",
  "Check if a Parentheses String Can Be Valid",
  "Reverse Substrings Between Each Pair of Parentheses",
  "Score of Parentheses",
  "Minimum Insertions to Balance a Parentheses String",
  "Longest Valid Parentheses",
  "Redundant Parenthesis",
  "Min Stack",
  "Maximum Frequency Stack",
  "Design a Stack With Increment Operation",
  "Dinner Plate Stacks",
  "Merge Intervals",
  "Insert Intervals",
  "Asteroid Collision",
  "Construct Smallest Number From DI String",
  "Evaluate Reverse Polish Notation",
  "Simplify Path",
  "Basic Calculator",
  "Basic Calculator II",
  "Basic Calculator IV",
  "Replace Non-Coprime Numbers in Array",
  "Robot Collisons",
  "Number of atoms",
  "Final Prices With a Special Discount in a Shop",
  "Next Greater Element I",
  "Next Greater Element II",
  "Next Greater Element IV",
  "Daily Temperatures",
  "Car Fleet",
  "Car Fleet II",
  "132 Pattern",
  "Smallest Subsequence of Distinct Characters",
  "Count Submatrices With All Ones",
  "Remove Duplicate Letters",
  "The Number of Weak Characters in the Game",
  "Maximum Subarray Min-Product",
  "Sum of Subarray Minimums",
  "Shortest Unsorted Continuous Subarray",
  "Remove K Digits",
  "Beautiful Towers I",
  "Beautiful Towers II",
  "Online Stock Span",
  "Minimum Number of Increments on Subarrays to Form a Target Array",
  "Maximum Score of a Good Subarray",
  "Number of Visible People in a Queue",
  "Trapping Rain Water",
  "Maximal Rectangle",
  "Largest Rectangle in Histogram",
  "Create Maximum Number",
  "Find Building Where Alice And Bob Can Meet",
  "Sum Of Total Strength Of Wizards",
  "Find the Number of Subarrays Where Boundary Elements Are Maximum",
  "C++ STL (queue)",
  "Implement Queue using Array",
  "Implement Stack using Queues",
  "Implement Queue using Stacks",
  "Queue using Two Stacks",
  "Implement Queue using Linked List",
  "Design Circular Queue",
  "Design Front Middle Back Queue",
  "N-Queue using Array",
  "Reverse First K Elements of Queue",
  "First Non-Repeating Character in a Stream",
  "First Negative Integer in Every Window of Size K",
  "Dota2 Senate",
  "Find the Winner of the Circular Game",
  "Reveal Cards in Increasing Order",
  "Minimum Number of K Consecutive Bit Flips",
  "Stamping the Sequence",
  "Deque Implementations",
  "Design Circular Deque",
  "Jump Game VI",
  "Continuous Subarrays",
  "Max Value of Equation",
  "Sliding Window Maximum",
  "Shortest Subarray with Sum at Least K",
  "Constrained Subsequence Sum",
  "Binary Search",
  "Guess Number Higher or Lower",
  "H-Index II",
  "Find First and Last Position of Element in Sorted Array",
  "Special Array With X Elements Greater Than or Equal X",
  "Find Smallest Letter Greater Than Target",
  "Longest Subsequence With Limited Sum",
  "First Bad Version",
  "Arranging Coins",
  "Find the Distance Value Between Two Arrays",
  "Search Insert Position",
  "Find Target Indices After Sorting Array",
  "Find Right Interval",
  "Online Election",
  "Most Beautiful Item for Each Query",
  "Time Based Key-Value Store",
  "Random Pick with Weight",
  "Plates Between Candles",
  "Successful Pairs of Spells and Potions",
  "Range Frequency Queries",
  "Minimum Operations to Make All Array Elements Equal",
  "Count Number of Rectangles Containing Each Point",
  "Count the Number of Fair Pairs",
  "Minimum Absolute Sum Difference",
  "Find the Longest Valid Obstacle Course at Each Position",
  "Find the Number of Subarrays Where Boundary Elements Are Maximum",
  "Count Negative Numbers in a Sorted Matrix",
  "Search a 2D Matrix",
  "Search a 2D Matrix II",
  "Median in a Row-wise Sorted Matrix",
  "Missing Number",
  "Kth Missing Positive Number",
  "Single Element in a Sorted Array",
  "Minimum Common Value",
  "Find the Duplicate Number",
  "Find Peak Element",
  "Find a Peak Element II",
  "Find Minimum in Rotated Sorted Array",
  "Peak Index in a Mountain Array",
  "Search in Rotated Sorted Array",
  "Search in Rotated Sorted Array II",
  "Rotation",
  "Find Minimum in Rotated Sorted Array II",
  "Find in Mountain Array",
  "Sqrt(x)",
  "Capacity to Ship Packages Within D Days",
  "Koko Eating Bananas",
  "Find the Smallest Divisor Given a Threshold",
  "Minimum Number of Days to Make M Bouquets",
  "Aggressive Cows",
  "Maximum Candies Allocated to K Children",
  "Most Profit Assigning Work",
  "Maximum Value at a Given Index in a Bounded Array",
  "Maximum Side Length of a Square With Sum Less Than or Equal to Threshold",
  "Minimum Speed to Arrive on Time",
  "Minimum Time to Repair Cars",
  "Maximum Number of Removable Characters",
  "Heaters",
  "Earliest Second to Mark Indices I",
  "Maximum White Tiles Covered by a Carpet",
  "Minimum Absolute Difference Between Elements with Constraint",
  "Sell Diminishing-Valued Colored Balls",
  "Ugly Number III",
  "Minimize the Maximum of Two Arrays",
  "Split Array Largest Sum",
  "Maximum Running Time of N Computers",
  "Maximum Number of Robots Within Budget",
  "Maximum Number of Groups With Increasing Length",
  "Maximum Number of Tasks You Can Assign",
  "Median of Two Sorted Arrays",
  "Magnetic Force Between Two Balls",
  "Maximum Tastiness of Candy Basket",
  "Minimum Limit of Balls in a Bag",
  "Minimized Maximum of Products Distributed to Any Store",
  "Minimize the Maximum Difference of Pairs",
  "Maximize the Minimum Powered City",
  "Kth Smallest Number in Multiplication Table",
  "Find K-th Smallest Pair Distance",
  "Kth Smallest Element in a Sorted Matrix",
  "Find the Median of the Uniqueness Array",
  "Kth Smallest Product of Two Sorted Arrays",
  "Kth Smallest Amount With Single Denomination Combination",
  "Find the Kth Smallest Sum of a Matrix With Sorted Rows",
  "Decimal to Binary",
  "Get, Set, Clear ith Bit",
  "Kth Bit is Set or Not",
  "Check Odd or Even",
  "Set the Rightmost Unset Bit",
  "Number Complement",
  "Number of 1 Bits",
  "Counting Bits",
  "Count Total Set Bits",
  "Reverse Bits",
  "Power of Two",
  "Power of Four",
  "Hamming Distance",
  "Add Binary",
  "Total Hamming Distance",
  "UTF-8 Validation",
  "Single Number II",
  "Divide Two Integers",
  "Decode Xored Array",
  "Single Number",
  "Single Number III",
  "Sum of Two Integers",
  "Swap Two Numbers (with Temp Variable)",
  "Missing Number",
  "Decode Xored Permutation",
  "Find the Original Array of Prefix XOR",
  "Gray Code",
  "XOR Queries of a Subarray",
  "XOR Sequences",
  "Minimum Number of Operations to Make Array XOR Equal to K",
  "Maximum XOR Product",
  "Neighboring Bitwise XOR",
  "Minimum XOR Sum of Two Arrays",
  "Find XOR Sum of All Pairs Bitwise AND",
  "Find Longest Awesome Substring",
  "Shortest Subarray with OR at Least K",
  "Minimum Array End",
  "Maximum OR",
  "Find Subarray with Bitwise OR Closest to K",
  "Minimize OR of Remaining Elements Using Operations",
  "Minimum Flips to Make A or B Equal to C",
  "Longest Nice Subarray",
  "Bitwise AND of Numbers Range",
  "Longest Subarray with Maximum Bitwise AND",
  "Number of Subarrays with AND Value of K",
  "Triples with Bitwise AND Equal to Zero",
  "Minimum Operations to Form Subsequence with Target Sum",
  "Power of Two",
  "Power of Three",
  "Power of Four",
  "Fibonacci Number",
  "Pow(x, n)",
  "Count Good Numbers",
  "Minimum Non-Zero Product of the Array Elements",
  "Delete Middle Element of a Stack",
  "Sort a Stack",
  "Josephus Problem",
  "Find the Winner of the Circular Game",
  "Predict the Winner",
  "Tower of Hanoi",
  "Different Ways to Add Parentheses",
  "Basic Calculator",
  "Permutation Sequence",
  "Regular Expression Matching",
  "Wildcard Matching",
  "Integer to English Words",
  "Special Binary String",
  "Permutations",
  "Construct Smallest Number from DI String",
  "Beautiful Arrangement",
  "Target Sum",
  "Combinations",
  "Letter Combinations of a Phone Number",
  "Letter Case Permutation",
  "K-th Lexicographical String of All Happy Strings of Length n",
  "Combination Sum",
  "Combination Sum II",
  "Combination Sum III",
  "Maximum Compatibility Score Sum",
  "Numbers with Same Consecutive Differences",
  "N-Queens",
  "Subsets",
  "Subsets II",
  "Non-Decreasing Subsequences",
  "Number of Beautiful Subsets",
  "Rat in a Maze Problem",
  "Sudoku Solver",
  "Binary Tree Preorder Traversal",
  "Binary Tree Inorder Traversal",
  "Binary Tree Postorder Traversal",
  "Preorder, Postorder, Inorder in a Single Traversal",
  "Remove Half Nodes",
  "Balanced Binary Tree",
  "Maximum Depth of Binary Tree",
  "Diameter of Binary Tree",
  "Count Complete Tree Nodes",
  "Minimum Depth of Binary Tree",
  "Check Completeness of a Binary Tree",
  "Construct Binary Tree from Parent Array",
  "Linked List to Binary Tree",
  "Construct Binary Tree from Preorder and Inorder Traversal",
  "Construct Binary Tree from Inorder and Postorder Traversal",
  "Construct Binary Tree from Preorder and Postorder Traversal",
  "Construct Binary Tree from String with Bracket Representation",
  "Same Tree",
  "Two Mirror Trees",
  "Merge Two Binary Trees",
  "Subtree of Another Tree",
  "Check if Tree is Isomorphic",
  "Leaf-Similar Trees",
  "Check if Subtree",
  "Mirror Tree",
  "Binary Tree Level Order Traversal",
  "Binary Tree Level Order Traversal II",
  "Cousins in Binary Tree",
  "Average of Levels in Binary Tree",
  "Minimum Number of Operations to Sort a Binary Tree by Level",
  "Binary Tree Right Side View",
  "Left View of Binary Tree",
  "Top View of Binary Tree",
  "Vertical Order Traversal of a Binary Tree",
  "Serialize and Deserialize Binary Tree",
  "All Nodes Distance K in Binary Tree",
  "Burning Tree",
  "Populating Next Right Pointers in Each Node",
  "Binary Tree Paths",
  "Path Sum",
  "Children Sum in a Binary Tree",
  "Path Sum II",
  "Sum Root to Leaf Numbers",
  "Binary Tree Maximum Path Sum",
  "Path Sum III",
  "Lowest Common Ancestor of a Binary Tree",
  "N-ary Tree",
  "N-ary Tree Postorder Traversal",
  "N-ary Tree Preorder Traversal",
  "Maximum Depth of N-ary Tree",
  "Search in a Binary Search Tree",
  "Insert into a Binary Search Tree",
  "Delete Node in a BST",
  "Convert Sorted Array to Binary Search Tree",
  "Convert Sorted List to Binary Search Tree",
  "Convert BST to Greater Tree",
  "Trim a Binary Search Tree",
  "Serialize and Deserialize BST",
  "Construct Binary Search Tree from Preorder Traversal",
  "Construct BST from Postorder",
  "Balance a Binary Search Tree",
  "Binary Search Tree to Greater Sum Tree",
  "Find Mode in Binary Search Tree",
  "Range Sum of BST",
  "Validate Binary Search Tree",
  "Minimum Distance Between BST Nodes",
  "Kth Smallest Element in a BST",
  "Increasing Order Search Tree",
  "Two Sum IV - Input is a BST",
  "Maximum Sum BST in Binary Tree",
  "Find Common Nodes in two BSTs",
  "All Elements in Two Binary Search Trees",
  "Unique Binary Search Trees",
  "Recover Binary Search Tree",
  "Number of Ways to Reorder Array to Get Same BST",
  "Binary Search Tree Iterator",
  "Lowest Common Ancestor of a Binary Search Tree",
  "Closest Nodes Queries in a Binary Search Tree",
  "Implementation of Priority Queue using Binary Heap",
  "Heap Sort",
  "Does Array Represent Heap?",
  "Is Binary Tree Heap?",
  "Operations on Binary Min Heap",
  "Convert Min Heap to Max Heap",
  "Relative Ranks",
  "Take Gifts From the Richest Pile",
  "Last Stone Weight",
  "Largest Number After Digit Swaps by Parity",
  "Minimum Amount of Time to Fill Cups",
  "Seat Reservation Manager",
  "Sort Characters By Frequency",
  "Reduce Array Size to The Half",
  "Longest Happy String",
  "Reorganize String",
  "Maximum Average Pass Ratio",
  "Find Score of an Array After Marking All Elements",
  "Furthest Building You Can Reach",
  "Distant Barcodes",
  "Task Scheduler",
  "Maximal Score After Applying K Operations",
  "Single Threaded CPU",
  "Most Popular Video Creator",
  "Total Cost to Hire K Workers",
  "Most Frequent IDs",
  "Process Tasks Using Servers",
  "Maximum Number of Eaten Apples",
  "Maximum Number of Events That Can Be Attended",
  "Minimum Operations to Exceed Threshold Value II",
  "Put Marbles in Bags",
  "Maximum Spending After Buying Items",
  "Trapping Rain Water II",
  "Maximum Subsequence Score",
  "Maximum Performance of a Team",
  "Max Value of Equation",
  "The Skyline Problem",
  "Maximum Elegance of a K-Length Subsequence",
  "The K Weakest Rows in a Matrix",
  "Kth Largest Element in an Array",
  "Kth Largest Element in a Stream",
  "Find Subsequence of Length K With the Largest Sum",
  "K-th Smallest Prime Fraction",
  "K Closest Points to Origin",
  "Top K Frequent Elements",
  "Kth Smallest Element in a Sorted Matrix",
  "Find Kth Largest XOR Coordinate Value",
  "Top K Frequent Words",
  "Find K Closest Elements",
  "Ugly Number II",
  "Find the Kth Largest Integer in the Array",
  "Reward Top K Students",
  "Query Kth Smallest Trimmed Number",
  "K Highest Ranked Items Within a Price Range",
  "Find the Kth Smallest Sum of a Matrix With Sorted Rows",
  "Find the K-Sum of an Array",
  "Remove Stones to Minimize the Total",
  "Minimum Operations to Halve Array Sum",
  "The Number of the Smallest Unoccupied Chair",
  "Lexicographically Minimum String After Removing Stars",
  "Replace Question Marks in String to Minimize Its Value",
  "Minimum Sum of Squared Difference",
  "Minimum Cost to Hire K Workers",
  "Minimize Deviation in Array",
  "Minimum Moves to Move a Box to Their Target Location",
  "Minimum Interval to Include Each Query",
  "Merge K Sorted Lists",
  "Find K Pairs with Smallest Sums",
  "Merge K Sorted Arrays",
  "Number of Orders in the Backlog",
  "Sliding Window Median",
  "IPO",
  "Find Median from Data Stream",
  "Meeting Rooms III",
  "Time to Cross a Bridge",
  "Implement Trie (Prefix Tree)",
  "Trie Delete",
  "Design Add and Search Words Data Structure",
  "Map Sum Pairs",
  "Maximum XOR of Two Numbers in an Array",
  "Minimum XOR Value Pair",
  "Maximum XOR With an Element From Array",
  "Count Pairs With XOR in a Range",
  "Maximum Strong Pair XOR II",
  "Longest Common Prefix",
  "Find the Length of the Longest Common Prefix",
  "Search Suggestions System",
  "Sum of Prefix Scores of Strings",
  "Prefix and Suffix Search",
  "Longest Common Suffix Queries",
  "Count Prefix and Suffix Pairs II",
  "Stream of Characters",
  "Extra Characters in a String",
  "Implement Magic Dictionary",
  "Number of Matching Subsequences",
  "Camelcase Matching",
  "Short Encoding of Words",
  "Encrypt and Decrypt Strings",
  "Longest Word in Dictionary",
  "Construct String With Minimum Cost",
  "Shortest Uncommon Substring in an Array",
  "Word Break",
  "Word Break II",
  "Word Search II",
  "Palindrome Pairs",
  "Remove Sub-Folders from the Filesystem",
  "Delete Duplicate Folders in System",
  "Maximum 69 Number",
  "Maximum Sum with Exactly K Elements",
  "Minimum Time to Type Word Using Special Typewriter",
  "Minimum Operations to Make the Array Increasing",
  "Minimum Number of Operations to Convert Time",
  "Assign Cookies",
  "Play with Chips",
  "Jump Game",
  "Jump Game II",
  "Wiggle Subsequence",
  "Cinema Seat Allocation",
  "Advantage Shuffle",
  "Minimum Score by Changing Two Elements",
  "Minimum Operations to Make Array Equal II",
  "Mice and Cheese",
  "Minimum Seconds to Equalize a Circular Array",
  "Maximum Bags with Full Capacity of Rocks",
  "Minimize Maximum of Array",
  "Minimum Platforms",
  "Fractional Knapsack",
  "Activity Selection",
  "Job Sequencing Problem",
  "Non-Overlapping Intervals",
  "Divide Intervals into Minimum Number of Groups",
  "Task Scheduler",
  "Minimum Number of Operations to Make Arrays Similar",
  "Minimum Cost for Cutting Cake II",
  "Patching Array",
  "Reverse Subarray to Maximize Array Value",
  "Super Washing Machines",
  "Minimum Cost to Equalize Array",
  "Optimal Partition of String",
  "Minimum Swaps to Make Strings Equal",
  "Maximum Number of Non-Overlapping Substrings",
  "Lexicographically Smallest Beautiful String",
  "Count K-Subsequences of a String with Maximum Beauty",
  "Bag of Tokens",
  "Boats to Save People",
  "Maximum Matching of Players with Trainers",
  "Candy",
  "Lemonade Change",
  "Gas Station",
  "Group the People Given the Group Size They Belong To",
  "Divide Array in Sets of K Consecutive Numbers",
  "Previous Permutation with One Swap",
  "Partition Labels",
  "Construct K Palindrome Strings",
  "Reorganize String",
  "String Without AAA or BBB",
  "Check If a String Can Break Another String",
  "Remove Duplicate Letters",
  "Largest Merge of Two Strings",
  "Shortest String That Contains Three Strings",
  "Lexicographically Smallest String After Substring Operation",
  "Minimum Rounds to Complete All Tasks",
  "Number of Burgers with No Waste of Ingredients",
  "Queue Reconstruction by Height",
  "Car Pooling",
  "Climbing Stairs",
  "Min Cost Climbing Stairs",
  "Perfect Squares",
  "Decode Ways",
  "Unique Binary Search Trees",
  "House Robber",
  "Coin Change",
  "Best Time to Buy and Sell Stock",
  "Minimum Cost For Tickets",
  "Delete and Earn",
  "Maximum Total Damage With Spell Casting",
  "Arithmetic Slices",
  "Longest Arithmetic Subsequence of Given Difference",
  "Partition Array for Maximum Sum",
  "Maximize Consecutive Elements in an Array After Modification",
  "Coin Change II",
  "Knight Dialer",
  "Partition Equal Subset Sum",
  "Triangle",
  "Student Attendance Record Leetcode",
  "Find the Maximum Length of a Good Subsequence II",
  "K Inverse Pairs Array",
  "Combination Sum IV",
  "Largest Sum of Averages",
  "Longest Arithmetic Subsequence",
  "Number of Dice Rolls With Target Sum",
  "Dice Roll Simulation",
  "Number of Strings Which Can Be Rearranged to Contain Substring",
  "Frog Jump",
  "Best Time to Buy and Sell Stock II",
  "Best Time to Buy and Sell Stock III",
  "Best Time to Buy and Sell Stock IV",
  "Freedom Trail",
  "Number of Music Playlists",
  "Count Vowels Permutation",
  "Best Time to Buy and Sell Stock with Transaction Fee",
  "Minimum Distance to Type a Word Using Two Fingers",
  "Minimum Difficulty of a Job Schedule",
  "Best Time to Buy and Sell Stock with Cooldown",
  "Number of Ways to Paint N × 3 Grid",
  "Build Array Where You Can Find The Maximum Exactly K Comparisons",
  "Number of Ways of Cutting a Pizza",
  "Paint House III",
  "Count All Possible Routes",
  "Geek's Training",
  "Unique Paths",
  "Unique Paths II",
  "Minimum Path Sum",
  "Maximum Non Negative Product in a Matrix",
  "Maximum Difference Score in a Grid",
  "Minimum Number of Operations to Satisfy Conditions",
  "Maximum Number of Moves in a Grid",
  "Where Will the Ball Fall",
  "Dungeon Game",
  "Cherry Pickup",
  "Number of Paths with Max Score",
  "Cherry Pickup II",
  "Minimum Falling Path Sum II",
  "Out of Boundary Paths",
  "Minimum Falling Path Sum",
  "Knapsack - 1",
  "Knapsack - 2",
  "Ones and Zeroes",
  "Target Sum",
  "2 Keys Keyboard",
  "Best Team With No Conflicts",
  "Shopping Offers",
  "Minimum Number of Coins for Fruits",
  "Last Stone Weight II",
  "Rod Cutting",
  "Filling Bookcase Shelves",
  "Video Stitching",
  "Maximize Total Cost of Alternating Subarrays",
  "Pizza With 3n Slices",
  "Minimum Swaps To Make Sequences Increasing",
  "Profitable Schemes",
  "Reducing Dishes",
  "Find Number of Ways to Reach the K-th Stair",
  "Find the Sum of Subsequence Powers",
  "Count of Sub-Multisets With Bounded Sum",
  "Longest Increasing Subsequence",
  "Printing Longest Increasing Subsequence",
  "Number of Longest Increasing Subsequence",
  "Largest Divisible Subset",
  "Longest Unequal Adjacent Groups Subsequence II",
  "Max Sum Increasing Subsequence",
  "Find the Maximum Length of Valid Subsequence II",
  "Wiggle Subsequence",
  "Find the Count of Monotonic Pairs I",
  "Russian Doll Envelopes",
  "Delete Columns to Make Sorted III",
  "Minimum Number of Removals to Make Mountain Array",
  "Maximum Height by Stacking Cuboids",
  "Maximum Length of Pair Chain",
  "Make Array Strictly Increasing",
  "Longest Common Subsequence",
  "Print all LCS sequences",
  "Count Common Subsequence in Two Strings",
  "Delete operation for two strings",
  "Longest Palindromic Substring",
  "Longest Palindromic Subsequence",
  "Maximum Length of Repeated Subarray",
  "Edit Distance",
  "Interleaving String",
  "Regular Expression Matching",
  "Wildcard Matching",
  "Shortest Common Supersequence",
  "Minimum Insertion Steps to Make a String Palindrome",
  "Max Dot Product of Two Subsequences",
  "Minimum Substring Partition of Equal Character Frequency",
  "Apply Operations to Make Two Strings Equal",
  "Minimum ASCII Delete Sum for Two Strings",
  "Word Break",
  "Longest String Chain",
  "Unique Substrings in Wraparound String",
  "Longest Valid Parentheses",
  "Distinct Subsequences",
  "Word Break II",
  "Sort an Array",
  "Concatenated Words",
  "Count Different Palindromic Subsequences",
  "Distinct Subsequences II",
  "Longest Chunked Palindrome Decomposition",
  "String Compression II",
  "Number of Ways to Form a Target String Given a Dictionary",
  "Minimum Changes to Make K Semi-palindromes",
  "Maximal Square",
  "Range Sum Query 2D - Immutable",
  "Largest Plus Sign",
  "Largest 1-Bordered Square",
  "Count Square Submatrices with All Ones",
  "Matrix Block Sum",
  "Count Submatrices With All Ones",
  "Ways to Make a Fair Array",
  "Maximal Rectangle",
  "Max Sum of Rectangle No Larger Than K",
  "Super Washing Machines",
  "Maximum Sum of 3 Non-Overlapping Subarrays",
  "Number of Submatrices That Sum to Target",
  "Find the Count of Monotonic Pairs II",
  "Get the Maximum Score",
  "Matrix Chain Multiplication",
  "Guess Number Higher or Lower II",
  "Predict the Winner",
  "Stone Game",
  "Burst Balloons",
  "Minimum Score Triangulation of Polygon",
  "Minimum Cost Tree From Leaf Values",
  "Partition Array for Maximum Sum",
  "Palindrome Partitioning II",
  "Stone Game VII",
  "Remove Boxes",
  "Strange Printer",
  "Valid Permutations for DI Sequence",
  "Minimum Cost to Merge Stones",
  "Allocate Mailboxes",
  "Minimum Cost to Cut a Stick",
  "Stone Game V",
  "Palindrome Partitioning III",
  "Maximum Subarray",
  "Maximum Product Subarray",
  "Bitwise ORs of Subarrays",
  "Longest Turbulent Subarray",
  "Maximum Subarray Sum with One Deletion",
  "K-Concatenation Maximum Sum",
  "Length of Longest Fibonacci Subsequence",
  "DFS Traversal",
  "Find if Path Exists in Graph",
  "Keys and Rooms",
  "Number of Provinces",
  "Count the Number of Complete Components",
  "Reorder Routes to Make All Paths Lead to the City Zero",
  "Longest Cycle in a Graph",
  "BFS in Graph",
  "Snakes and Ladders",
  "Open the Lock",
  "Round Trip ",
  "Word Ladder",
  "Valid BFS?",
  "Count the Number of Houses at a Certain Distance I",
  "As Far from Land as Possible",
  "Minimum Operations to Convert Number",
  "Minimum Score of a Path Between Two Cities",
  "Shortest Path with Alternating Colors",
  "Minimum Number of Operations to Make X and Y Equal",
  "Shortest Path Visiting All Nodes",
  "Jump Game III",
  "Clone Graph",
  "Last Day Where You Can Still Cross",
  "Sliding Puzzle",
  "Maximum Candies You Can Get from Boxes",
  "Shortest Path to Get All Keys",
  "Jump Game IV",
  "Word Ladder II",
  "Escape the Spreading Fire",
  "Detect Cycle in an Undirected Graph (GeeksforGeeks)",
  "Detect Cycle in a Directed Graph (GeeksforGeeks)",
  "Check if a Graph Has a Cycle of Odd Length",
  "Detect Cycles in 2D Grid",
  "Shortest Cycle in a Graph",
  "Is Graph Bipartite?",
  "Possible Bipartition",
  "Flower Planting With No Adjacent",
  "Divide Nodes into the Maximum Number of Groups",
  "Course Schedule",
  "Course Schedule II",
  "Find Eventual Safe States",
  "Minimum Height Trees",
  "Loud and Rich",
  "All Ancestors of a Node in a Directed Acyclic Graph",
  "Find All Possible Recipes from Given Supplies",
  "Alien Dictionary ",
  "Longest Increasing Path in a Matrix",
  "Cat and Mouse",
  "Sort Items by Groups Respecting Dependencies",
  "Sort Items by Groups Respecting Dependencies",
  "Largest Color Value in a Directed Graph",
  "Parallel Courses III",
  "Parallel Courses II",
  "Number of Increasing Paths in a Grid",
  "Build a Matrix With Conditions",
  "Flood Fill",
  "Island Perimeter",
  "Battleships in a Board",
  "Number of Islands",
  "Max Area of Island",
  "Count Sub Islands",
  "Find All Groups of Farmland",
  "Rotting Oranges",
  "Number of Enclaves",
  "Map of Highest Peak",
  "Surrounded Regions",
  "Number of Closed Islands",
  "01 Matrix",
  "Shortest Bridge",
  "Shortest Route I",
  "Dijkstra? ",
  "Investigation",
  "Flight Discount",
  "Network Delay Time",
  "Cheapest Flights Within K Stops",
  "Number of Ways to Arrive at Destination",
  "Path with Maximum Probability",
  "Path with Minimum Effort",
  "Number of Restricted Paths from First to Last Node",
  "Reachable Nodes in Subdivided Graph",
  "Minimum Cost to Make at Least One Valid Path in a Grid",
  "Minimum Obstacle Removal to Reach Corner",
  "Shortest Path in Binary Matrix",
  "Nearest Exit from Entrance in Maze",
  "Minimum Cost to Make at Least One Valid Path in a Grid",
  "Second Minimum Time to Reach Destination",
  "High Score ",
  "Cycle Finding",
  "Bus Routes",
  "Road Construction",
  "Course Schedule IV",
  "Find the City With the Smallest Number of Neighbors at a Threshold Distance",
  "Count the Number of Houses at a Certain Distance I",
  "Minimum Cost to Convert String I",
  "Greg and Array",
  "Design Graph With Shortest Path Calculator",
  "Number of Possible Sets of Closing Branches",
  "Find the Shortest Superstring",
  "Redundant Connection",
  "Satisfiability of Equality Equations",
  "Smallest String With Swaps",
  "Accounts Merge",
  "Most Stones Removed with Same Row or Column",
  "Find Latest Group of Size M",
  "Redundant Connection II",
  "Making a Large Island",
  "GCD Sort of an Array",
  "Bricks Falling When Hit",
  "Checking Existence of Edge Length Limited Paths",
  "Remove Max Number of Edges to Keep Graph Fully Traversable",
  "Rank Transform of a Matrix",
  "Prim’s Minimum Spanning Tree (MST) – Greedy Algorithm ",
  "Kruskal’s Minimum Spanning Tree Algorithm – Greedy Algorithm ",
  "Minimum Spanning Tree ",
  "Min Cost to Connect All Points",
  "Water Connection Problem ",
  "Connecting Cities with Minimum Cost",
  "Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree",
  "Remove Max Number of Edges to Keep Graph Fully Traversable",
  "Articulation Points (or Cut Vertices) in a Graph ",
  "Strongly Connected Components",
  "Critical Connections in a Network",
  "Check if it is a Straight Line",
  "Minimum Lines to Represent a Line Chart",
  "K Closest Points to Origin",
  "Check If Two Line Segments Intersect",
  "Max Points on a Line",
  "Minimize Manhattan Distances",
  "Self Crossing",
  "Rectangle Overlap",
  "Largest Triangle Area",
  "Minimum Rectangles to Cover Points",
  "Rectangle Area",
  "Minimum Area Rectangle",
  "Minimum Area Rectangle II",
  "Mirror Reflection",
  "Find the Largest Area of Square Inside Two Rectangles",
  "Minimum Cuts to Divide a Circle",
  "Generate Random Point in a Circle",
  "Circle and Rectangle Overlapping",
  "Count Lattice Points Inside a Circle",
  "Queries on Number of Points Inside a Circle",
  "Maximum Number of Darts Inside of a Circular Dartboard",
  "Factorial of Large Numbers",
  "nCr Mod m",
  "Tiles",
  "Distribute Candies Among Children II ",
  "Unique Paths",
  " Right Triangles",
  "Permutation Sequence ",
  "Count Anagrams ",
  "Number of Ways to Reorder Array to Get Same BST",
  "Count the Number of Ideal Arrays ",
  "Count All Valid Pickup and Delivery Options",
  "Bitwise OR of All Subsequence Sums",
  "Count the Arrays",
  "Beautiful Numbers",
  "String Mark",
  "Divisor Game",
  "Nim Game",
  "Find the Winning Player in Coin Game",
  "Yet Another String Game",
  "Substring Removal Game",
  "Sasha and Sticks",
  "Card Game",
  "01 Game",
  "Digit Game",
  "Can I Win",
  "Guess Number Higher or Lower II",
  "Maximum Number of Coins You Can Get",
  "Remove Colored Pieces if Both Neighbors are the Same Color",
  "Digit Game",
  "Dinner With Emma",
  "Matrix Game",
  "Sequential Game",
  "Ping-pong",
  "Godsend",
  "PolandBall and Game",
  "Even-Odd Game",
  "Palindrome Game",
  "Cat and Mouse",
  "Cat and Mouse II",
  "Guess the Word",
  "Can I Win",
  "Partition to K Equal Sum Subsets",
  "Stickers to Spell Word",
  "Smallest Sufficient Team",
  "Maximum Students Taking Exam",
  "Number of Ways to Wear Different Hats to Each Other",
  "Minimum Cost to Connect Two Groups of Points",
  "Maximum Number of Achievable Transfer Requests",
  "Little Elephant and T-Shirts",
  "Distribute Repeating Integers",
  "Maximize Grid Happiness",
  "Find Minimum Time to Finish All Jobs",
  "Minimum Sum of Values by Dividing Array",
  "Shortest Path Visiting All Nodes",
  "Grouping",
  "Matching",
  "Counting Numbers",
  "Non-negative Integers without Consecutive Ones",
  "Numbers At Most N Given Digit Set",
  "Numbers With Repeated Digits",
  "Number of Digit One",
  "Number of Beautiful Integers in the Range",
  "Count the Number of Powerful Integers",
  "Find All Good Strings",
  "House Robber III",
  "Longest ZigZag Path in a Binary Tree",
  "Maximum Score After Applying Operations on a Tree",
  "Subordinates",
  "Tree Matching",
  "Maximum Sum BST in Binary Tree",
  "Number of Ways to Reorder Array to Get Same BST",
  "Maximum Points After Collecting Coins From All Nodes",
  "Sum of Distances in Tree",
  "Maximum Points After Collecting Coins From All Nodes",
  "Count Paths That Can Form a Palindrome in a Tree",
  "Find Number of Coins to Place in Tree Nodes",
  "Minimize the Total Price of the Trips",
  "Tree Distances 1",
  "Tree Distances II",
  "Company Queries I",
  "Company Queries II",
  "Distance Queries",
  "Time Taken to Mark All Nodes",
  "Ugly Number II",
  "Count Sorted Vowel Strings",
  "Race Car",
  "Super Egg Drop",
  "Least Operators to Express Number",
  "Largest Multiple of Three",
  "Kth Smallest Instructions",
  "Number of Sets of K Non-Overlapping Line Segments",
  "Domino and Tromino Tiling",
  "Count Numbers with Unique Digits",
  "Minimum One Bit Operations to Make Integers Zero",
  "Find All Possible Stable Binary Arrays II",
  "Counting Tilings",
  "Soup Servings",
  "New 21 Game",
  "Airplane Seat Assignment Probability",
  "Knight Probability in Chessboard",
  "Champagne Tower",
  "Sushi",
  "Coins",
  "Probability of a Two Boxes Having the Same Number of Distinct Balls",
  "KMP Algorithm for Pattern Searching",
  "Rabin-Karp Algorithm for Pattern Searching",
  "Z Algorithm (Linear-Time Pattern Searching Algorithm)",
  "Count Prefix and Suffix Pairs II",
  "Number of Subarrays That Match a Pattern II",
  "Minimum Time to Revert Word to Initial State II",
  "Find Beautiful Indices in the Given Array II",
  "String Transformation",
  "Find Substring with Given Hash Value",
  "Maximum Deletions on a String",
  "Match Substring After Replacement",
  "Sum of Scores of Built Strings",
  "Find All Good Strings",
  "Longest Happy Prefix",
  "Shortest Palindrome",
  "Distinct Echo Substrings",
  "Longest Chunked Palindrome Decomposition",
  "Maximum Product of the Length of Two Palindromic Substrings",
  "Longest Duplicate Substring",
  "Alternating Groups III",
  "Number of Pairs Satisfying Inequality",
  "Count Good Triplets in an Array",
  "Booking Concert Tickets in Groups",
  "Longest Uploaded Prefix",
];

const data2 = [
  "Partition Array According to Given Pivot",
  "Rearrange Array Elements by Sign",
  "3Sum Closest",
  "4Sum",
  "Sort Colors",
  "Container With Most Water",
  "Watering Plants II",
  "Next Permutation",
  "Next Greater Element III",
  "Reverse Words in a String",
  "Largest Merge of Two Strings",
  "Make String a Subsequence Using Cyclic Increments",
  "Minimum Length of String After Deleting Similar Ends",
  "String Compression",
  "Separate Black and White Balls",
  "Move Pieces to Obtain a String",
  "Sentence Similarity III",
  "Count Vowel Strings in Ranges",
  "Minimum Penalty for a Shop",
  "Find Good Days to Rob the Bank",
  "Sum of Absolute Differences in a Sorted Array",
  "Product of Array Except Self",
  "Product of the Last K Numbers",
  "Removing Minimum Number of Magic Beans",
  "Find All Good Indices",
  "Movement of Robots",
  "Range Sum Query 2D - Immutable",
  "Increment Submatrices by One",
  "Power of Heroes",
  "Minimum Cost to Make Array Equal",
  "Pongal Bunk",
  "Car Pooling",
  "My Calendar II",
  "Shifting Letters II",
  "Perfect Rectangle",
  "Rectangle Area II",
  "Number of Flowers in Full Bloom",
  "Set Matrix Zeroes",
  "Sort the Matrix Diagonally",
  "Minimum Operations to Write the Letter Y on a Grid",
  "Rotate Image",
  "Rotating the Box",
  "Cyclically Rotating a Grid",
  "Game of Life",
  "Find Valid Matrix Given Row and Column Sums",
  "Queens That Can Attack the King",
  "Max Increase to Keep City Skyline",
  "Count Submatrices with Top-Left Element and Sum Less Than k",
  "Find the Minimum Area to Cover All Ones I",
  "Find the Minimum Area to Cover All Ones II",
  "Valid Sudoku",
  "Check if Move is Legal",
  "Valid Tic-Tac-Toe State",
  "Number of Laser Beams in a Bank",
  "Where Will the Ball Fall",
  "Image Overlap",
  "Minimum Operations to Make a Uni-Value Grid",
  "Equal Row and Column Pairs",
  "Difference Between Ones and Zeros in Row and Column",
  "Diagonal Traverse",
  "Matrix Block Sum",
  "Maximum Sum of an Hourglass",
  "Maximum Matrix Sum",
  "Find the Grid of Region Average",
  "Spiral Matrix",
  "Spiral Matrix II",
  "Replace Elements in an Array",
  "Count the Number of Special Characters II",
  "Reconstruct Original Digits from English",
  "Integer to Roman",
  "Sort Characters by Frequency",
  "HTML Entity Parser",
  "Group Anagrams",
  "Majority Element II",
  "Find All Lonely Numbers in the Array",
  "First Missing Positive",
  "Shortest Impossible Sequence of Rolls",
  "Find Occurrences of an Element in an Array",
  "Groups of Special Equivalent Strings",
  "Word Subsets",
  "Find the Maximum Number of Elements in Subset",
  "People Whose List of Favorite Companies is Not a Subset of Another List",
  "Count the Number of Good Partitions",
  "Optimal Partition of String",
  "Custom Sort String",
  "Finding the Users Active Minutes",
  "Convert an Array into a 2D Array with Conditions",
  "Group the People Given the Group Size They Belong To",
  "Evaluate the Bracket Pairs of a String",
  "Minimum Number of Operations to Make Word K-Periodic",
  "Can Convert String in K Moves",
  "Restore the Array from Adjacent Pairs",
  "Tuple with Same Product",
  "Split the Array to Make Coprime Products",
  "4Sum II",
  "Count Artifacts That Can Be Extracted",
  "Brick Wall",
  "Pairs of Songs with Total Durations Divisible by 60",
  "Alphabet Board Path",
  "Vowel Spellchecker",
  "Bulls and Cows",
  "Card Flipping Game",
  "Maximum Size of a Set After Removals",
  "Minimum Absolute Difference Queries",
  "Check if Array Pairs are Divisible by K",
  "Count Pairs That Form a Complete Day II",
  "Count Number of Bad Pairs",
  "Minimum Seconds to Equalize a Circular Array",
  "Sum of Imbalance Numbers of All Subarrays",
  "Grid Illumination",
  "Maximum Equal Frequency",
  "Rearranging Fruits",
  "Subarray Sum Equals K",
  "Subarray Sums Divisible by K",
  "Make Sum Divisible by P",
  "Count Number of Bad Pairs",
  "Continuous Subarray Sum",
  "Count of Interesting Subarrays",
  "Count Number of Nice Subarrays",
  "Count Beautiful Substrings II",
  "Sum of Digit Differences of All Pairs",
  "Binary Subarrays with Sum",
  "Number of Wonderful Substrings",
  "Count the Number of Beautiful Subarrays",
  "Number of Submatrices That Sum to Target",
  "Count Subarrays with Median K",
  "Find All Anagrams in a String",
  "Permutation in String",
  "Check If a String Contains All Binary Codes of Size K",
  "Maximum Number of Vowels in a Substring of Given Length",
  "Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold",
  "K Radius Subarray Averages",
  "Maximum Sum of Distinct Subarrays With Length K",
  "Sliding Subarray Beauty",
  "Maximum Points You Can Obtain from Cards",
  "Sliding Window Median",
  "Sliding Window Maximum",
  "Max Value of Equation",
  "Maximum Sum of 3 Non-Overlapping Subarrays",
  "Longest Substring Without Repeating Characters",
  "Longest Repeating Character Replacement",
  "Maximum Number of Occurrences of a Substring",
  "Max Consecutive Ones III",
  "Count the Number of Substrings With Dominant Ones",
  "Minimum Window Substring",
  "Substring with Concatenation of All Words",
  "Minimum Size Subarray Sum",
  "Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit",
  "Fruit Into Baskets",
  "Subarray Product Less Than K",
  "Grumpy Bookstore Owner",
  "Moving Stones Until Consecutive II",
  "Count Number of Nice Subarrays",
  "Number of Subarrays with Bounded Maximum",
  "Maximum Erasure Value",
  "Longest Subarray of 1's After Deleting One Element",
  "Count the Number of Good Subarrays",
  "Minimum Consecutive Cards to Pick Up",
  "Minimum Operations to Reduce X to Zero",
  "Frequency of the Most Frequent Element",
  "Subarrays with K Different Integers",
  "Minimum Add to Make Parentheses Valid",
  "Minimum Remove to Make Valid Parentheses",
  "Maximum Nesting Depth of Two Valid Parentheses Strings",
  "Check if a Parentheses String Can Be Valid",
  "Reverse Substrings Between Each Pair of Parentheses",
  "Score of Parentheses",
  "Minimum Insertions to Balance a Parentheses String",
  "Longest Valid Parentheses",
  "Redundant Parenthesis",
  "Min Stack",
  "Maximum Frequency Stack",
  "Design a Stack With Increment Operation",
  "Dinner Plate Stacks",
  "Merge Intervals",
  "Insert Intervals",
  "Asteroid Collision",
  "Construct Smallest Number From DI String",
  "Evaluate Reverse Polish Notation",
  "Simplify Path",
  "Basic Calculator",
  "Basic Calculator II",
  "Basic Calculator IV",
  "Replace Non-Coprime Numbers in Array",
  "Robot Collisons",
  "Number of atoms",
  "Final Prices With a Special Discount in a Shop",
  "Next Greater Element I",
  "Next Greater Element II",
  "Next Greater Element IV",
  "Daily Temperatures",
  "Car Fleet",
  "Car Fleet II",
  "132 Pattern",
  "Smallest Subsequence of Distinct Characters",
  "Count Submatrices With All Ones",
  "Remove Duplicate Letters",
  "The Number of Weak Characters in the Game",
  "Maximum Subarray Min-Product",
  "Sum of Subarray Minimums",
  "Shortest Unsorted Continuous Subarray",
  "Remove K Digits",
  "Beautiful Towers I",
  "Beautiful Towers II",
  "Online Stock Span",
  "Minimum Number of Increments on Subarrays to Form a Target Array",
  "Maximum Score of a Good Subarray",
  "Number of Visible People in a Queue",
  "Trapping Rain Water",
  "Maximal Rectangle",
  "Largest Rectangle in Histogram",
  "Create Maximum Number",
  "Find Building Where Alice And Bob Can Meet",
  "Sum Of Total Strength Of Wizards",
  "Find the Number of Subarrays Where Boundary Elements Are Maximum",
  "First Negative Integer in Every Window of Size K",
  "Dota2 Senate",
  "Find the Winner of the Circular Game",
  "Reveal Cards in Increasing Order",
  "Minimum Number of K Consecutive Bit Flips",
  "Stamping the Sequence",
  "Design Circular Deque",
  "Jump Game VI",
  "Continuous Subarrays",
  "Max Value of Equation",
  "Sliding Window Maximum",
  "Shortest Subarray with Sum at Least K",
  "Constrained Subsequence Sum",
  "H-Index II",
  "Find Right Interval",
  "Online Election",
  "Most Beautiful Item for Each Query",
  "Time Based Key-Value Store",
  "Random Pick with Weight",
  "Plates Between Candles",
  "Successful Pairs of Spells and Potions",
  "Range Frequency Queries",
  "Minimum Operations to Make All Array Elements Equal",
  "Count Number of Rectangles Containing Each Point",
  "Count the Number of Fair Pairs",
  "Minimum Absolute Sum Difference",
  "Find the Longest Valid Obstacle Course at Each Position",
  "Find the Number of Subarrays Where Boundary Elements Are Maximum",
  "Search a 2D Matrix",
  "Search a 2D Matrix II",
  "Median in a Row-wise Sorted Matrix",
  "Single Element in a Sorted Array",
  "Find the Duplicate Number",
  "Find Peak Element",
  "Find a Peak Element II",
  "Find Minimum in Rotated Sorted Array",
  "Peak Index in a Mountain Array",
  "Search in Rotated Sorted Array",
  "Search in Rotated Sorted Array II",
  "Rotation",
  "Find Minimum in Rotated Sorted Array II",
  "Find in Mountain Array",
  "Capacity to Ship Packages Within D Days",
  "Koko Eating Bananas",
  "Find the Smallest Divisor Given a Threshold",
  "Minimum Number of Days to Make M Bouquets",
  "Aggressive Cows",
  "Maximum Candies Allocated to K Children",
  "Most Profit Assigning Work",
  "Maximum Value at a Given Index in a Bounded Array",
  "Maximum Side Length of a Square With Sum Less Than or Equal to Threshold",
  "Minimum Speed to Arrive on Time",
  "Minimum Time to Repair Cars",
  "Maximum Number of Removable Characters",
  "Heaters",
  "Earliest Second to Mark Indices I",
  "Maximum White Tiles Covered by a Carpet",
  "Minimum Absolute Difference Between Elements with Constraint",
  "Sell Diminishing-Valued Colored Balls",
  "Ugly Number III",
  "Minimize the Maximum of Two Arrays",
  "Split Array Largest Sum",
  "Maximum Running Time of N Computers",
  "Maximum Number of Robots Within Budget",
  "Maximum Number of Groups With Increasing Length",
  "Maximum Number of Tasks You Can Assign",
  "Median of Two Sorted Arrays",
  "Magnetic Force Between Two Balls",
  "Maximum Tastiness of Candy Basket",
  "Minimum Limit of Balls in a Bag",
  "Minimized Maximum of Products Distributed to Any Store",
  "Minimize the Maximum Difference of Pairs",
  "Maximize the Minimum Powered City",
  "Kth Smallest Number in Multiplication Table",
  "Find K-th Smallest Pair Distance",
  "Kth Smallest Element in a Sorted Matrix",
  "Find the Median of the Uniqueness Array",
  "Kth Smallest Product of Two Sorted Arrays",
  "Kth Smallest Amount With Single Denomination Combination",
  "Find the Kth Smallest Sum of a Matrix With Sorted Rows",
  "Pow(x, n)",
  "Minimum Non-Zero Product of the Array Elements",
  "Sort a Stack",
  "Find the Winner of the Circular Game",
  "Predict the Winner",
  "Tower of Hanoi",
  "Different Ways to Add Parentheses",
  "Basic Calculator",
  "Permutation Sequence",
  "Regular Expression Matching",
  "Wildcard Matching",
  "Integer to English Words",
  "Special Binary String",
  "Permutations",
  "Construct Smallest Number from DI String",
  "Beautiful Arrangement",
  "Target Sum",
  "Combinations",
  "Letter Combinations of a Phone Number",
  "Letter Case Permutation",
  "K-th Lexicographical String of All Happy Strings of Length n",
  "Combination Sum",
  "Combination Sum II",
  "Combination Sum III",
  "Maximum Compatibility Score Sum",
  "Numbers with Same Consecutive Differences",
  "N-Queens",
  "Subsets",
  "Subsets II",
  "Non-Decreasing Subsequences",
  "Number of Beautiful Subsets",
  "Rat in a Maze Problem",
  "Sudoku Solver",
  "Check Completeness of a Binary Tree",
  "Construct Binary Tree from Parent Array",
  "Linked List to Binary Tree",
  "Construct Binary Tree from Preorder and Inorder Traversal",
  "Construct Binary Tree from Inorder and Postorder Traversal",
  "Construct Binary Tree from Preorder and Postorder Traversal",
  "Construct Binary Tree from String with Bracket Representation",
  "Check if Subtree",
  "Mirror Tree",
  "Binary Tree Level Order Traversal",
  "Binary Tree Level Order Traversal II",
  "Minimum Number of Operations to Sort a Binary Tree by Level",
  "Top View of Binary Tree",
  "Vertical Order Traversal of a Binary Tree",
  "Serialize and Deserialize Binary Tree",
  "All Nodes Distance K in Binary Tree",
  "Burning Tree",
  "Populating Next Right Pointers in Each Node",
  "Children Sum in a Binary Tree",
  "Path Sum II",
  "Sum Root to Leaf Numbers",
  "Binary Tree Maximum Path Sum",
  "Path Sum III",
  "Lowest Common Ancestor of a Binary Tree",
  "Insert into a Binary Search Tree",
  "Delete Node in a BST",
  "Convert Sorted List to Binary Search Tree",
  "Convert BST to Greater Tree",
  "Trim a Binary Search Tree",
  "Serialize and Deserialize BST",
  "Construct Binary Search Tree from Preorder Traversal",
  "Construct BST from Postorder",
  "Balance a Binary Search Tree",
  "Binary Search Tree to Greater Sum Tree",
  "Validate Binary Search Tree",
  "Kth Smallest Element in a BST",
  "Maximum Sum BST in Binary Tree",
  "Find Common Nodes in two BSTs",
  "All Elements in Two Binary Search Trees",
  "Unique Binary Search Trees",
  "Recover Binary Search Tree",
  "Number of Ways to Reorder Array to Get Same BST",
  "Binary Search Tree Iterator",
  "Lowest Common Ancestor of a Binary Search Tree",
  "Closest Nodes Queries in a Binary Search Tree",
  "Heap Sort",
  "Is Binary Tree Heap?",
  "Operations on Binary Min Heap",
  "Convert Min Heap to Max Heap",
  "Seat Reservation Manager",
  "Sort Characters By Frequency",
  "Reduce Array Size to The Half",
  "Longest Happy String",
  "Reorganize String",
  "Maximum Average Pass Ratio",
  "Find Score of an Array After Marking All Elements",
  "Furthest Building You Can Reach",
  "Distant Barcodes",
  "Task Scheduler",
  "Maximal Score After Applying K Operations",
  "Single Threaded CPU",
  "Most Popular Video Creator",
  "Total Cost to Hire K Workers",
  "Most Frequent IDs",
  "Process Tasks Using Servers",
  "Maximum Number of Eaten Apples",
  "Maximum Number of Events That Can Be Attended",
  "Minimum Operations to Exceed Threshold Value II",
  "Put Marbles in Bags",
  "Maximum Spending After Buying Items",
  "Trapping Rain Water II",
  "Maximum Subsequence Score",
  "Maximum Performance of a Team",
  "Max Value of Equation",
  "The Skyline Problem",
  "Maximum Elegance of a K-Length Subsequence",
  "Kth Largest Element in an Array",
  "K-th Smallest Prime Fraction",
  "K Closest Points to Origin",
  "Top K Frequent Elements",
  "Kth Smallest Element in a Sorted Matrix",
  "Find Kth Largest XOR Coordinate Value",
  "Top K Frequent Words",
  "Find K Closest Elements",
  "Ugly Number II",
  "Find the Kth Largest Integer in the Array",
  "Reward Top K Students",
  "Query Kth Smallest Trimmed Number",
  "K Highest Ranked Items Within a Price Range",
  "Find the Kth Smallest Sum of a Matrix With Sorted Rows",
  "Find the K-Sum of an Array",
  "Remove Stones to Minimize the Total",
  "Minimum Operations to Halve Array Sum",
  "The Number of the Smallest Unoccupied Chair",
  "Lexicographically Minimum String After Removing Stars",
  "Replace Question Marks in String to Minimize Its Value",
  "Minimum Sum of Squared Difference",
  "Minimum Cost to Hire K Workers",
  "Minimize Deviation in Array",
  "Minimum Moves to Move a Box to Their Target Location",
  "Minimum Interval to Include Each Query",
  "Merge K Sorted Lists",
  "Find K Pairs with Smallest Sums",
  "Merge K Sorted Arrays",
  "Number of Orders in the Backlog",
  "Sliding Window Median",
  "IPO",
  "Find Median from Data Stream",
  "Meeting Rooms III",
  "Time to Cross a Bridge",
  "Implement Trie (Prefix Tree)",
  "Trie Delete",
  "Design Add and Search Words Data Structure",
  "Map Sum Pairs",
  "Longest Common Prefix",
  "Find the Length of the Longest Common Prefix",
  "Search Suggestions System",
  "Sum of Prefix Scores of Strings",
  "Prefix and Suffix Search",
  "Longest Common Suffix Queries",
  "Count Prefix and Suffix Pairs II",
  "Stream of Characters",
  "Extra Characters in a String",
  "Implement Magic Dictionary",
  "Number of Matching Subsequences",
  "Camelcase Matching",
  "Short Encoding of Words",
  "Encrypt and Decrypt Strings",
  "Longest Word in Dictionary",
  "Construct String With Minimum Cost",
  "Shortest Uncommon Substring in an Array",
  "Word Break",
  "Word Break II",
  "Word Search II",
  "Palindrome Pairs",
  "Remove Sub-Folders from the Filesystem",
  "Delete Duplicate Folders in System",
  "Jump Game",
  "Jump Game II",
  "Wiggle Subsequence",
  "Cinema Seat Allocation",
  "Advantage Shuffle",
  "Minimum Score by Changing Two Elements",
  "Minimum Operations to Make Array Equal II",
  "Mice and Cheese",
  "Minimum Seconds to Equalize a Circular Array",
  "Maximum Bags with Full Capacity of Rocks",
  "Minimize Maximum of Array",
  "Minimum Platforms",
  "Fractional Knapsack",
  "Activity Selection",
  "Job Sequencing Problem",
  "Non-Overlapping Intervals",
  "Divide Intervals into Minimum Number of Groups",
  "Task Scheduler",
  "Minimum Number of Operations to Make Arrays Similar",
  "Minimum Cost for Cutting Cake II",
  "Patching Array",
  "Reverse Subarray to Maximize Array Value",
  "Super Washing Machines",
  "Minimum Cost to Equalize Array",
  "Optimal Partition of String",
  "Minimum Swaps to Make Strings Equal",
  "Maximum Number of Non-Overlapping Substrings",
  "Lexicographically Smallest Beautiful String",
  "Count K-Subsequences of a String with Maximum Beauty",
  "Bag of Tokens",
  "Boats to Save People",
  "Maximum Matching of Players with Trainers",
  "Candy",
  "Gas Station",
  "Group the People Given the Group Size They Belong To",
  "Divide Array in Sets of K Consecutive Numbers",
  "Previous Permutation with One Swap",
  "Partition Labels",
  "Construct K Palindrome Strings",
  "Reorganize String",
  "String Without AAA or BBB",
  "Check If a String Can Break Another String",
  "Remove Duplicate Letters",
  "Largest Merge of Two Strings",
  "Shortest String That Contains Three Strings",
  "Lexicographically Smallest String After Substring Operation",
  "Minimum Rounds to Complete All Tasks",
  "Number of Burgers with No Waste of Ingredients",
  "Queue Reconstruction by Height",
  "Car Pooling",
  "Perfect Squares",
  "Decode Ways",
  "Unique Binary Search Trees",
  "House Robber",
  "Coin Change",
  "Minimum Cost For Tickets",
  "Delete and Earn",
  "Maximum Total Damage With Spell Casting",
  "Arithmetic Slices",
  "Longest Arithmetic Subsequence of Given Difference",
  "Partition Array for Maximum Sum",
  "Maximize Consecutive Elements in an Array After Modification",
  "Coin Change II",
  "Knight Dialer",
  "Partition Equal Subset Sum",
  "Triangle",
  "Student Attendance Record Leetcode",
  "Find the Maximum Length of a Good Subsequence II",
  "K Inverse Pairs Array",
  "Combination Sum IV",
  "Largest Sum of Averages",
  "Longest Arithmetic Subsequence",
  "Number of Dice Rolls With Target Sum",
  "Dice Roll Simulation",
  "Number of Strings Which Can Be Rearranged to Contain Substring",
  "Frog Jump",
  "Best Time to Buy and Sell Stock II",
  "Best Time to Buy and Sell Stock III",
  "Best Time to Buy and Sell Stock IV",
  "Freedom Trail",
  "Number of Music Playlists",
  "Count Vowels Permutation",
  "Best Time to Buy and Sell Stock with Transaction Fee",
  "Minimum Distance to Type a Word Using Two Fingers",
  "Minimum Difficulty of a Job Schedule",
  "Best Time to Buy and Sell Stock with Cooldown",
  "Number of Ways to Paint N × 3 Grid",
  "Build Array Where You Can Find The Maximum Exactly K Comparisons",
  "Number of Ways of Cutting a Pizza",
  "Paint House III",
  "Count All Possible Routes",
  "Geek's Training",
  "Unique Paths",
  "Unique Paths II",
  "Minimum Path Sum",
  "Maximum Non Negative Product in a Matrix",
  "Maximum Difference Score in a Grid",
  "Minimum Number of Operations to Satisfy Conditions",
  "Maximum Number of Moves in a Grid",
  "Where Will the Ball Fall",
  "Dungeon Game",
  "Cherry Pickup",
  "Number of Paths with Max Score",
  "Cherry Pickup II",
  "Minimum Falling Path Sum II",
  "Out of Boundary Paths",
  "Minimum Falling Path Sum",
  "Knapsack - 1",
  "Knapsack - 2",
  "Ones and Zeroes",
  "Target Sum",
  "2 Keys Keyboard",
  "Best Team With No Conflicts",
  "Shopping Offers",
  "Minimum Number of Coins for Fruits",
  "Last Stone Weight II",
  "Rod Cutting",
  "Filling Bookcase Shelves",
  "Video Stitching",
  "Maximize Total Cost of Alternating Subarrays",
  "Pizza With 3n Slices",
  "Minimum Swaps To Make Sequences Increasing",
  "Profitable Schemes",
  "Reducing Dishes",
  "Find Number of Ways to Reach the K-th Stair",
  "Find the Sum of Subsequence Powers",
  "Count of Sub-Multisets With Bounded Sum",
  "Longest Increasing Subsequence",
  "Printing Longest Increasing Subsequence",
  "Number of Longest Increasing Subsequence",
  "Largest Divisible Subset",
  "Longest Unequal Adjacent Groups Subsequence II",
  "Max Sum Increasing Subsequence",
  "Find the Maximum Length of Valid Subsequence II",
  "Wiggle Subsequence",
  "Find the Count of Monotonic Pairs I",
  "Russian Doll Envelopes",
  "Delete Columns to Make Sorted III",
  "Minimum Number of Removals to Make Mountain Array",
  "Maximum Height by Stacking Cuboids",
  "Maximum Length of Pair Chain",
  "Make Array Strictly Increasing",
  "Longest Common Subsequence",
  "Print all LCS sequences",
  "Count Common Subsequence in Two Strings",
  "Theory",
  "Delete operation for two strings",
  "Longest Palindromic Substring",
  "Longest Palindromic Subsequence",
  "Maximum Length of Repeated Subarray",
  "Edit Distance",
  "Interleaving String",
  "Regular Expression Matching",
  "Wildcard Matching",
  "Shortest Common Supersequence",
  "Minimum Insertion Steps to Make a String Palindrome",
  "Max Dot Product of Two Subsequences",
  "Minimum Substring Partition of Equal Character Frequency",
  "Apply Operations to Make Two Strings Equal",
  "Minimum ASCII Delete Sum for Two Strings",
  "Word Break",
  "Longest String Chain",
  "Unique Substrings in Wraparound String",
  "Longest Valid Parentheses",
  "Distinct Subsequences",
  "Word Break II",
  "Sort an Array",
  "Concatenated Words",
  "Count Different Palindromic Subsequences",
  "Distinct Subsequences II",
  "Longest Chunked Palindrome Decomposition",
  "String Compression II",
  "Number of Ways to Form a Target String Given a Dictionary",
  "Minimum Changes to Make K Semi-palindromes",
  "Maximal Square",
  "Range Sum Query 2D - Immutable",
  "Largest Plus Sign",
  "Largest 1-Bordered Square",
  "Count Square Submatrices with All Ones",
  "Matrix Block Sum",
  "Count Submatrices With All Ones",
  "Ways to Make a Fair Array",
  "Maximal Rectangle",
  "Max Sum of Rectangle No Larger Than K",
  "Super Washing Machines",
  "Maximum Sum of 3 Non-Overlapping Subarrays",
  "Number of Submatrices That Sum to Target",
  "Find the Count of Monotonic Pairs II",
  "Get the Maximum Score",
  "Matrix Chain Multiplication",
  "Guess Number Higher or Lower II",
  "Predict the Winner",
  "Stone Game",
  "Burst Balloons",
  "Minimum Score Triangulation of Polygon",
  "Minimum Cost Tree From Leaf Values",
  "Partition Array for Maximum Sum",
  "Palindrome Partitioning II",
  "Stone Game VII",
  "Remove Boxes",
  "Strange Printer",
  "Valid Permutations for DI Sequence",
  "Minimum Cost to Merge Stones",
  "Allocate Mailboxes",
  "Minimum Cost to Cut a Stick",
  "Stone Game V",
  "Palindrome Partitioning III",
  "Maximum Subarray",
  "Maximum Product Subarray",
  "Bitwise ORs of Subarrays",
  "Longest Turbulent Subarray",
  "Maximum Subarray Sum with One Deletion",
  "K-Concatenation Maximum Sum",
  "Length of Longest Fibonacci Subsequence",
  "Keys and Rooms",
  "Number of Provinces",
  "Count the Number of Complete Components",
  "Reorder Routes to Make All Paths Lead to the City Zero",
  "Longest Cycle in a Graph",
  "Snakes and Ladders",
  "Open the Lock",
  "Round Trip",
  "Word Ladder",
  "Valid BFS?",
  "Count the Number of Houses at a Certain Distance I",
  "As Far from Land as Possible",
  "Minimum Operations to Convert Number",
  "Minimum Score of a Path Between Two Cities",
  "Shortest Path with Alternating Colors",
  "Minimum Number of Operations to Make X and Y Equal",
  "Shortest Path Visiting All Nodes",
  "Jump Game III",
  "Clone Graph",
  "Last Day Where You Can Still Cross",
  "Sliding Puzzle",
  "Maximum Candies You Can Get from Boxes",
  "Shortest Path to Get All Keys",
  "Jump Game IV",
  "Word Ladder II",
  "Escape the Spreading Fire",
  "Detect Cycle in an Undirected Graph (GeeksforGeeks)",
  "Detect Cycle in a Directed Graph (GeeksforGeeks)",
  "Check if a Graph Has a Cycle of Odd Length",
  "Detect Cycles in 2D Grid",
  "Shortest Cycle in a Graph",
  "Is Graph Bipartite?",
  "Possible Bipartition",
  "Flower Planting With No Adjacent",
  "Divide Nodes into the Maximum Number of Groups",
  "Course Schedule",
  "Course Schedule II",
  "Find Eventual Safe States",
  "Minimum Height Trees",
  "Loud and Rich",
  "All Ancestors of a Node in a Directed Acyclic Graph",
  "Find All Possible Recipes from Given Supplies",
  "Alien Dictionary",
  "Longest Increasing Path in a Matrix",
  "Cat and Mouse",
  "Sort Items by Groups Respecting Dependencies",
  "Sort Items by Groups Respecting Dependencies",
  "Largest Color Value in a Directed Graph",
  "Parallel Courses III",
  "Parallel Courses II",
  "Number of Increasing Paths in a Grid",
  "Build a Matrix With Conditions",
  "Battleships in a Board",
  "Number of Islands",
  "Max Area of Island",
  "Count Sub Islands",
  "Find All Groups of Farmland",
  "Rotting Oranges",
  "Number of Enclaves",
  "Map of Highest Peak",
  "Surrounded Regions",
  "Number of Closed Islands",
  "01 Matrix",
  "Shortest Bridge",
  "Shortest Route I",
  "Dijkstra?",
  "Investigation",
  "Flight Discount",
  "Network Delay Time",
  "Cheapest Flights Within K Stops",
  "Number of Ways to Arrive at Destination",
  "Path with Maximum Probability",
  "Path with Minimum Effort",
  "Number of Restricted Paths from First to Last Node",
  "Reachable Nodes in Subdivided Graph",
  "Minimum Cost to Make at Least One Valid Path in a Grid",
  "Minimum Obstacle Removal to Reach Corner",
  "Shortest Path in Binary Matrix",
  "Nearest Exit from Entrance in Maze",
  "Minimum Cost to Make at Least One Valid Path in a Grid",
  "Second Minimum Time to Reach Destination",
  "High Score",
  "Cycle Finding",
  "Bus Routes",
  "Road Construction",
  "Course Schedule IV",
  "Find the City With the Smallest Number of Neighbors at a Threshold Distance",
  "Count the Number of Houses at a Certain Distance I",
  "Minimum Cost to Convert String I",
  "Greg and Array",
  "Design Graph With Shortest Path Calculator",
  "Number of Possible Sets of Closing Branches",
  "Find the Shortest Superstring",
  "Redundant Connection",
  "Satisfiability of Equality Equations",
  "Smallest String With Swaps",
  "Accounts Merge",
  "Most Stones Removed with Same Row or Column",
  "Find Latest Group of Size M",
  "Redundant Connection II",
  "Making a Large Island",
  "GCD Sort of an Array",
  "Bricks Falling When Hit",
  "Checking Existence of Edge Length Limited Paths",
  "Remove Max Number of Edges to Keep Graph Fully Traversable",
  "Rank Transform of a Matrix",
  "Prim’s Minimum Spanning Tree (MST) – Greedy Algorithm",
  "Theory",
  "Kruskal’s Minimum Spanning Tree Algorithm – Greedy Algorithm",
  "Theory",
  "Minimum Spanning Tree",
  "Min Cost to Connect All Points",
  "Water Connection Problem",
  "Connecting Cities with Minimum Cost",
  "Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree",
  "Remove Max Number of Edges to Keep Graph Fully Traversable",
];

function getRandomTitle(titles) {
  if (!Array.isArray(titles) || titles.length === 0) return null;
  const randomIndex = Math.floor(Math.random() * titles.length);
  return titles[randomIndex];
}

//data2 have 795 count
console.log(getRandomTitle(data2));


